### ISSUE TITLE
help.cpp Help_Security == Help_Nothing

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfo#106]
V524 It is odd that the body of 'Help_Security' function is fully equivalent to the body of 'Help_Nothing' function. help.cpp 159

![2016-12-09 11_12_43-no file and no file - araxis merge](https://cloud.githubusercontent.com/assets/920705/21042114/7b0960e2-be00-11e6-85c4-ee93b04b3501.png)

**Comment by JeromeMartinez** [comment]
Definitely an issue, and actually  'Help_Security' is orphan and should be removed
