### ISSUE TITLE
MediaInfo standalone binary

### ISSUE THREAD

**Issue by jhshadi** [MediaArea/MediaInfo#110]
Not sure if this is the place to ask but i'm trying to build and compile MediaInfo to one standalone binary with all the dependancies bundled up inside it so no further installations will be required on Ubuntu 12.04.

I have followed the readme file and got the mediaInfo executable but when i try to run it i get:
`error while loading shared libraries: libzen.so.0: cannot open shared object file: No such file or directory`

any help?

**Comment by tribouille** [comment]
Hi,

it means you have compiled MediaInfo with the ZenLib in shared mode.

If you want ZenLib in a shared mode, you need to set your LD_LIBRARY_PATH in your environment (export LD_LIBRARY_PATH=/path/to/ZenLib/shared/library/directory:$LD_LIBRARY_PATH) or set it up with ldconfig.

If you want to use static library, you need to ensure you compiled ZenLib with --enable-static for the configure step, MediaInfoLib with --enable-static --enable-staticlibs and MediaInfo with --enable-staticlibs.

**Comment by jhshadi** [comment]
Work like a charm, @tribouille thanks man!

**Comment by JeromeMartinez** [comment]
For reference, the "[./CLI_Compile.sh](https://github.com/MediaArea/MediaInfo/blob/master/Project/GNU/CLI/AddThisToRoot_CLI_compile.sh)" script in the "[All in one](https://mediaarea.net/fr/MediaInfo/Download/Source)" package contains these options by default, for this purpose.

> Not sure if this is the place to ask 

It is :).

> I have followed the readme file

[I added a ticket about that](https://github.com/MediaArea/MediaInfo/issues/111).
