### ISSUE TITLE
More details about static build in README

### ISSUE THREAD

**Issue by JeromeMartinez** [MediaArea/MediaInfo#111]
[This comment](https://github.com/MediaArea/MediaInfo/issues/110#issuecomment-271350912) should go in the READM as an alternative/example for compiling with different options.

**Comment by g-maxime** [comment]
The README already contains static build procedure (when building own ZenLib and MediaInfoLib), I add more documentation on this option.

**Comment by g-maxime** [comment]
Added in #114
