### ISSUE TITLE
Display different informations for the same JPEG image with and without IPTC

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfo#127]
It's not a request, just a remark, as i guess your priority is video, and in a less mesure audio. 

Just the fact of deleting the IPTC informations make MediaInfo identify differently the color space and the chroma subsampling.

As a side note, it recognize this uncompressed JPEG as lossy, but your "Compression" information display is perhaps based on the Huffman tables and in that case it's correct (Baseline DCT).

[PROBLEM.zip](https://github.com/MediaArea/MediaInfo/files/778521/PROBLEM.zip)

**Comment by JeromeMartinez** [comment]
> It's not a request, just a remark, as i guess your priority is video, and in a less mesure audio.

All issue are important

> Just the fact of deleting the IPTC informations make MediaInfo identify differently the color space and the chroma subsampling.

Issue is that this is the only source of information.
Windows 10 displays files differently:
![yccb](https://cloud.githubusercontent.com/assets/1641638/23070594/d9a43066-f52b-11e6-953a-eb7774e92c62.png)

FFmpeg detects yuvj420p or yuvj444p depending of the file too (but decoding has same colors, weird; only chroma changes)

> As a side note, it recognize this uncompressed JPEG as lossy, but your "Compression" information display is perhaps based on the Huffman tables and in that case it's correct (Baseline DCT).

Hum: is it really lossless? (uncompressed?) uncompressed does not mean lossless (it can be lossy if it is 444 cut to 420 uncompress), do you have a method proving that you can have the source file back when you decompress? Please provide source file, tool for converting to jpg, and tool for converting back from jpg to source file, so I can see it is lossless.

**Comment by JeromeMartinez** [comment]
Note that I don't expect to see "true JPEG" being lossless: I read https://en.wikipedia.org/wiki/Lossless_JPEG and lossles JPEG is for JPEG-2000 reversible and JPEG-LS. I am curious about a lossless .jpg file (I don't know a lot, I don't say it does not exist, just that I don't know it).

**Comment by Sami32** [comment]
To be honest it's was downloaded from Internet, as most of my tests file used for our media server.

I used [ExifTool](http://www.sno.phy.queensu.ca/~phil/exiftool/) ans [JPEG snoop](http://www.impulseadventure.com/photo/jpeg-snoop.html) to acceed to the images informations.

**Comment by Sami32** [comment]
@JeromeMartinez If i believe [this post](http://stackoverflow.com/questions/11723466/lossless-jpeg-cant-find-any-example-images-dicom-files) they are difficult to get :
> Lossless JPEG is most widely used in XA (cathlab) cine images. These are always grayscale, and exist as 8 or 10 bit images.

BTW, perhaps you will be interested by that sample ;) Though you have it already ?
Opus embedded in MPEGTS (i didn't even know about that before met this file and read [that](https://en.wikipedia.org/wiki/Opus_(audio_format)))
[opus.ts.txt](https://github.com/MediaArea/MediaInfo/files/783937/opus.ts.txt)

**Comment by Sami32** [comment]
@JeromeMartinez OK, finally an answer was given here:
http://stackoverflow.com/questions/38391049/libjpeg-and-lossless-jpeg

That make sens why they difficult to get, as a working library fully implementing the standard seem hard to find...

**Comment by ValZapod** [comment]
You also removed APP14 in lune72_noIPTC.jpg which signaled YUVK (or, more accurately it is named YCCK). That is why there is such a discrepancy. YCCK --> CMYK is not done. And ffmpeg is broken, just like our Chromium/Chrome. https://trac.ffmpeg.org/ticket/9085

**Comment by ValZapod** [comment]
This can be closed @JeromeMartinez. There is no bug here.

```
08CF21 FFEE - APPE - Application-specific marker 14 - Adobe (16 bytes)
08CF21  Header (4 bytes)
08CF21   Marker:                               65518 (0xFFEE)
08CF23   Fl - Frame header length:             14 (0x000E)
08CF25  Name:                                  Adobe
08CF2B  Version:                               100 (0x64)
08CF2C  flags0:                                16384 (0x4000)
08CF2E  flags1:                                0 (0x0000)
08CF30  transform:                             2 (0x02)
```

> FFmpeg detects yuvj420p or yuvj444p depending of the file too

It is now seeing yuvj420p or **yuva444p**, interesting, that may be the bug I was looking for!
