### ISSUE TITLE
Unknown video codec in ShockWave container

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfo#137]
Play fine in Web browser (Firefox):
https://sourceforge.net/projects/eclipsetutorial/
[Eclipse and Java for Total Beginners Lesson 1.7z.txt](https://github.com/MediaArea/MediaInfo/files/846345/Eclipse.and.Java.for.Total.Beginners.Lesson.1.7z.txt)

Audio is recognized as MP3 and play fine. VLC (2.0.8) say that it as 2 different video streams, one being Motion JPEG and the other undefined.
It seem that it has been created with _Camstasio Studio 5.0_.

As i don't know if it's an expected result, so feel free to close that issue if it's not appropriate. Thanks.

**Comment by JeromeMartinez** [comment]
As SWF is nearly dead, I don't see any interest in working on it, I close the issue but anyone do not hesitate to open again the issue if there is any interested in it.
