### ISSUE TITLE
Audio bit per sample ==> Bit0 ??? (in WMA, ASF, WMV)

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfo#139]
I don't know what to think about that. Is that an expected result on such audio files ?

Audio files samples here:
[acid_cbr12.asf.txt](https://github.com/MediaArea/MediaInfo/files/853706/acid_cbr12.asf.txt)
[Message_2020.wma.txt](https://github.com/MediaArea/MediaInfo/files/853708/Message_2020.wma.txt)

VLC report it as 32-bit.

**Comment by JeromeMartinez** [comment]
[Fixed](https://github.com/MediaArea/MediaInfoLib/commit/756c4f4d7c646c751b8da5207cc864c845d5c793).
