### ISSUE TITLE
Audio bitrate not detected in Speex

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfo#140]
Here is one sample:
[talk109-q5.spx.txt](https://github.com/MediaArea/MediaInfo/files/853829/talk109-q5.spx.txt)

No bit depth informations as well.
_PotPlayer_ identify it as 28.2 kHz and 16-bit

**EDIT**: No bitrate in this ADPCM stream as well:
[stereo_44k.flv.txt](https://github.com/MediaArea/MediaInfo/files/853843/stereo_44k.flv.txt)

**Comment by JeromeMartinez** [comment]
I don't see any interest in working on a workaround, I close the issue but anyone does not hesitate to open again the issue if there is any interested in it.

PS: please 1 ticket per format
