### ISSUE TITLE
No audio sample frequency detected in a RealAudio Lossless stream

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfo#141]
Here is the sample:
[luckynight.rmvb.txt](https://github.com/MediaArea/MediaInfo/files/853861/luckynight.rmvb.txt)

Identified as 44100 Hz and 16-bit by PotPlayer.

**Comment by JeromeMartinez** [comment]
RealAudio Lossless is not analyzed, and such piece of metadata is not available in the container, need to analyze the stream.

As RM is nearly dead, I don't see any interest in working on a workaround, I close the issue but anyone do not hesitate to open again the issue if there is any interested in it.
