### ISSUE TITLE
No  "duration" detected in some WMV files

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfo#142]
Here is the sample:
[data1.wmv.txt](https://github.com/MediaArea/MediaInfo/files/855085/data1.wmv.txt)

I guess that if the duration is not indicated in the Shorten, Atrac, ADTS or MLP formats, it's because there are raw streams not fully parsed, but in this WMV case that's look weird to me.
So perhaps this file is only malformed or corrupt ? In that case this issue is invalid and should be closed.

**Comment by JeromeMartinez** [comment]
The "play duration" is set to 0, so another method should be used for computing play duration (e.g. check the last packet duration?).
Note that e.g. VLC shows no duration too.

As WMV is nearly dead, I don't see any interest in working on a workaround, I close the issue but anyone does not hesitate to open again the issue if there is any interested in it.

**Comment by JeromeMartinez** [comment]
@Sami32 please use https://github.com/MediaArea/MediaInfoLib/issues about file detection, this project ("MediaInfo") is about the interfaces (GUI, CLI, DLL...)

**Comment by Sami32** [comment]
@JeromeMartinez OK. Thank you for taking time to explain :+1: 

Sorry for the inconvenience 8/

**Comment by JeromeMartinez** [comment]
@Sami32 no problem, knowing the limits and having sample files is good, keep doing it even if I close some (note: I close because I don't see myself interest, but as it is reference anyone could say he is interested in removing this limitation).
