### ISSUE TITLE
Am I the only person who finds this thing a pain to work with?

### ISSUE THREAD

**Issue by emotionally-exhausted** [MediaArea/MediaInfo#163]
Mediainfo is NOT case-insensitive! I type "mediainfo" at the command line and (I'll copy and paste here) it tells me to use "MediaInfo --Help". When I enter this exactly as shown I get "zsh: command not found: MediaInfo
".

I've wasted five minutes trying different variations of upper and lower case and still can't get the help menu to appear. I've used Media info before but abandoned it because it is a major nuisance getting the syntax right. I was hoping somebody would have corrected this by now, but it appears not so I guess I'll have to try and figure out some other way to inject the data into my scripts. Pity, because it is quite the comprehensive program, just not worth the inconsistent and mostly unneeded capitalization.

**Comment by JeromeMartinez** [comment]
> Mediainfo is NOT case-insensitive! 

Actually it depends of the OS, MediaInfo was originally developed on Windows which is case-insensitive.

> I've used Media info before but abandoned it because

It is a bit harsh. Anyway I understand the issue, we just weren't aware of it as there was no report about ot, and we'll fix it (I guess, using the program name instead of hardcoded name).

**Comment by kieranjol** [comment]
Have you added a filename after
`mediainfo`
Eg
`mediainfo /home/emotiontional/exhausted.mov`
?

That prompt that you get when you type lowercase `mediainfo ` is expected.
You haven't provided a file to analyse so what else is mediainfo supposed
to show you?

**Comment by emotionally-exhausted** [comment]
I thought that, like many other programs, it would display a help menu (silly me) that at the very least would show the usage syntax.

**Comment by JeromeMartinez** [comment]
Closed by https://github.com/MediaArea/MediaInfo/pull/164.
Testable with [snapshots](https://mediaarea.net/download/snapshots/binary/).

**Comment by emotionally-exhausted** [comment]
I'm afraid the issue goes far deeper than just the starting of the program.
I've always had problems getting Mediainfo to work properly, which is why I
stopped using it. I'm afraid you'll have to go through the whole program to
make it case-insensitive for Gnu/Linux users.

**Comment by JeromeMartinez** [comment]
> I've always had problems getting Mediainfo to work properly

Thousands of Linux/Mac (case insensitive OS) people already use MediaInfo without issue about any case intensive stuff (and the uppercases in the help part was not a problem), so please stop complaining this way if you want to be listened.

> I'm afraid you'll have to go through the whole program to make it case-insensitive for Gnu/Linux users.

This is not an issue report.
Please make an explicit issue report:
- What do you try to do
- Which command do you launch
- Which result do you have
- Which result is expected

> which is why I stopped using it. 

At some point, I'll stop trying to understand issues without correct explanation from people keeping complaining about small issues as if it is the end of the world, and especially with the price the person paid for the software.

**Comment by kieranjol** [comment]
I still don't get this issue. We use mediainfo in the same python scripts that run on various versions of Ubuntu/Windows/OSX flawlessly. This has never been an issue in any way.
