### ISSUE TITLE
CLI exit

### ISSUE THREAD

**Issue by retokromer** [MediaArea/MediaInfo#17]
I suggest that the correct commands `mediainfo --Version` and `mediainfo --Help` exit with a non-error flag.

**Comment by JeromeMartinez** [comment]
You detected the copy/paste of the code from MediaInfo to MediaConch ;-).

**Comment by retokromer** [comment]
Actually it's the contrary! I am using MediaInfo since long-time and have a lot of automated stuff that checks the exits (**non** for help and version). Therefore I am hypersensitive on exits ;-)
