### ISSUE TITLE
Two central "Front" in channel positions with AAC SBR-PS stream

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfo#175]
Do that result was expected with AAC SBR-PS ?
> Channel(s)                               : 2 channels / 1 channel / 1 channel
> Channel positions                        : Front: L R / Front: C / Front: C

If the 2 "front" are fine, please, feel free to close this issue.

[Alarm_Antelope_SBR-PS_v4.aac.txt](https://github.com/MediaArea/MediaInfo/files/1157624/Alarm_Antelope_SBR-PS_v4.aac.txt)

**Comment by ValZapod** [comment]
This is not printed now.
