### ISSUE TITLE
Force rescan

### ISSUE THREAD

**Issue by decorate** [MediaArea/MediaInfo#187]
I am getting information about DVDs using the command line on Windows and intermittently MediaInfo is using some form of cache to return a response. The information is for the previous DVD rather than the current one in the drive. Is there an option to force a media rescan?

**Comment by JeromeMartinez** [comment]
We don't use any cache, we use only [file management functions from Windows](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858(v=vs.85).aspx).
I don't see any method in API doc for clearing any cache, looks like more a Windows bug (or feature?) than a MediaInfo bug.

**Comment by decorate** [comment]
Thanks for the response. I think my problem is coming from sharing the drive with a running virtual machine (as I also run a Linux only command).
