### ISSUE TITLE
Namespace in EBUCore output doesn't match XSD namespace

### ISSUE THREAD

**Issue by bitsgalore** [MediaArea/MediaInfo#197]
EBUCore output generated by the latest version of the MediaInfo Command line tool  (MediaInfoLib - v0.7.99) doesn't validate against its XSD schema. Example:

    mediainfo --Output=EBUCore whatever.flac > mediainfo.xml

Then (using [jhove](http://jhove.openpreservation.org/)):

    jhove -m XML-hul mediainfo.xml > jhove.txt

Resulting output contains various error messages, which all appear to be caused by the fact that MediaInfo uses the namespace  'urn:ebu:metadata-schema:ebuCore_2017', whereas this namespace is declared as 'urn:ebu:metadata-schema:ebucore' (without the '_2017' suffix) in the XSD. See e.g.:

    ErrorMessage: TargetNamespace.1: Expecting namespace 'urn:ebu:metadata-schema:ebuCore_2017', but the target namespace of the schema document is 'urn:ebu:metadata-schema:ebucore'.: Line = 4, Column = 47
      ErrorMessage: cvc-elt.1: Cannot find the declaration of element 'ebucore:ebuCoreMain'.: Line = 3, Column = 476
      ErrorMessage: TargetNamespace.1: Expecting namespace 'urn:ebu:metadata-schema:ebuCore_2017', but the target namespace of the schema document is 'urn:ebu:metadata-schema:ebucore'.: Line = 4, Column = 47

Don't know whether this is really a bug or intentional behaviour (if I recall correctly an older MediaInfo version used a similar '_2015' suffix).

(Full JHOVE output attached here: [jhove.txt](https://github.com/MediaArea/MediaInfo/files/1434202/jhove.txt))

**Comment by JeromeMartinez** [comment]
Definitely some validation issues, not normal as it was validating when it is implemented, I work on that

**Comment by JeromeMartinez** [comment]
MediaInfo was using the draft of EBUCore 1.8, and it was modified at the last minute.
[Fixed](https://github.com/MediaArea/MediaInfoLib/pull/661).
Note that in previous MediaInfo version, you can use previous EBUCore version with ` --Output=EBUCore_1.6`
