### ISSUE TITLE
Directory contains \n makes complete name buggy

### ISSUE THREAD

**Issue by ahmedtds** [MediaArea/MediaInfo#220]
This bug happens with 18.03, previous release didn't have this bug.

Let's say you opened a file with mediainfo in this directory: C:\new
Then Complete name section in the text report will be buggy. I think \n in the path causes that.
I'm using Windows and Mediainfo GUI

**Comment by JeromeMartinez** [comment]
Maybe a stupid question, but how do you create such directory name?

**Comment by ahmedtds** [comment]
What do you mean?
You can just right click and New->Folder and make its name something starts with n, that's all. \ is not actually part of the folder name. Any folder name starts with n makes the path looks like that and for some reason that causes some bug after 18.03

**Comment by JeromeMartinez** [comment]
OK, got it, I thought that \n is for a carriage return (classic way to do code it).
We can reproduce the (very bad) bug, working on a fix.

**Comment by JeromeMartinez** [comment]
Fix in hotfix release 18.03.1

**Comment by ahmedtds** [comment]
Thanks for the quick fix!
