### ISSUE TITLE
Provided installers doesn't work (but software is)

### ISSUE THREAD

**Issue by gacelperfinian** [MediaArea/MediaInfo#231]
Configuration:
Version: Windows 10 Fall Creators' Update
MediaInfo Installer (to be installed): 18.03.1 (tested in 17.12)
Additional Configuration: Yes, following settings applied (As required in an enterprise computer, use `set-ProcessMitigation -PolicyFilePath FILE.xml` in PowerShell to import.)

To enable the configuration:
```
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <SystemConfig>
    <DEP Enable="true" EmulateAtlThunks="false" OverrideDEP="true"></DEP>
    <ASLR Enable="true" ForceRelocateImages="true" OverrideForceRelocateImages="true" BottomUp="true" HighEntropy="true" OverrideBottomUp="true"></ASLR>
    <ControlFlowGuard Enable="true" SuppressExports="true" OverrideCFG="true" StrictControlFlowGuard="false" OverrideStrictCFG="false"></ControlFlowGuard>
    <SEHOP Enable="true" TelemetryOnly="false" OverrideSEHOP="true"></SEHOP>
    <Heap TerminateOnError="true" OverrideHeap="true"></Heap>
  </SystemConfig>
</root>
```

To disable the configuration:
```
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <SystemConfig>
    <DEP Enable="true" EmulateAtlThunks="false" OverrideDEP="false"></DEP>
    <ASLR Enable="true" ForceRelocateImages="true" OverrideForceRelocateImages="false" BottomUp="true" HighEntropy="true" OverrideBottomUp="false"></ASLR>
    <ControlFlowGuard Enable="true" SuppressExports="false" OverrideCFG="false" StrictControlFlowGuard="false" OverrideStrictCFG="false"></ControlFlowGuard>
    <SEHOP Enable="true" TelemetryOnly="false" OverrideSEHOP="false"></SEHOP>
    <Heap TerminateOnError="true" OverrideHeap="false"></Heap>
  </SystemConfig>
</root>
```

Other NSIS-based software installers do work so I don't have a clue on why this *particular* software don't work. Note that I've downloaded the portable versions and they do work, so the installer is the culprit.

**Comment by JeromeMartinez** [comment]
> Provided installers doesn't work

We have thousands of installs per days, lot of them on Win10. So the generic title is too vague.

> As required in an enterprise computer

This may be the issue.
The installer needs admin rights, do you have them?

**Comment by gacelperfinian** [comment]
Yes, I've tried them on multiple computers and they don't start as intended. It spawns several processes but it eventually ends abruply.

**Comment by gacelperfinian** [comment]
Btw, does the installer use .NET components? (It would be weird on a NSIS installer though, I think .NET components are disabled for no apparent reason)

**Comment by JeromeMartinez** [comment]
> multiple computers

from the same enterprise (same config)?

For the moment, we don't plan to dig more on that, as it is very localized, at least on free support.
You may be interested in [professional support](http://mediaarea.net/Services) if you want dedicated analysis.

> does the installer use .NET components? 

No, just NSIS. another possibility would be that the installer is killed due to trying to check if a new version exists (1 anonymous call to mediaarea.net website).

**Comment by gacelperfinian** [comment]
> from the same enterprise (same config)?

Yes, it is!

Closing this for now as this is indeed too localized. Probably we will check the source later and deploy it when these settings are temporarily off. Thank you anyway!

**Comment by Smurfy82** [comment]
Hello,

this bug report is quite old but still exists. Installer crashes without error. Tracking down the bug ends at an old NSIS version, here 2.46.5

NSIS crashes if ASLR is Force Enabled. Manually disabling ASLR or overriding per App Settings results fixed the crash, installer works fine.

Updating NSIS to a newer or the newest version should fix this.

**Comment by JeromeMartinez** [comment]
> Updating NSIS to a newer or the newest version should fix this.

We [updated NSIS installer to 3.08](https://github.com/MediaArea/MediaArea-Utils-Binaries/pull/8), you may try [this dev snapshot](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20230411-3/MediaInfo_GUI_23.03.20230411_Windows.exe) which has this update.

**Comment by Smurfy82** [comment]
> you may try [this dev snapshot](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20230411-3/MediaInfo_GUI_23.03.20230411_Windows.exe) which has this update.

This dev snapshot still crashes. It was created with Nullsoft Install System v2.46.5-Unicode.

**Comment by JeromeMartinez** [comment]
@Smurfy82 sorry, mistake in the build, [this dev snapshot](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20230412/MediaInfo_GUI_23.03.20230412_Windows.exe) is with NSIS 3.08 (`<description>Nullsoft Install System v3.08</description>` checked in the binary).

**Comment by Smurfy82** [comment]
@JeromeMartinez Yes, the dev snapshot works fine. 👍
