### ISSUE TITLE
18.05 Qt GUI file not installed by make install

### ISSUE THREAD

**Issue by Vascom** [MediaArea/MediaInfo#238]
Qt version builded correctly but not installed by make
```
make install INSTALL_ROOT=/home/vascom/rpmbuild/BUILDROOT/mediainfo-18.05-1.fc28.x86_64
make: Nothing to be done for 'install'.
```
Files are present
```
$ ls /home/vascom/rpmbuild/BUILD/MediaInfo/Project/QMake/GUI/
AppxManifest.xml  _Automated  Makefile  mediainfo-gui  mediainfo-gui.rc  MediaInfoQt.pro
```
I run make install from /home/vascom/rpmbuild/BUILD/MediaInfo/Project/QMake/GUI/ directory.

**Comment by g-maxime** [comment]
Patch: https://github.com/MediaArea/MediaInfo/pull/239/commits/b5b6baf0708a3b13bb2c05fb5b6d22923831c94e

This can be also added to qmake command line

**Comment by Vascom** [comment]
OK
