### ISSUE TITLE
how to use it as lib

### ISSUE THREAD

**Issue by rahmanshaber** [MediaArea/MediaInfo#241]
i want to use it as a lib in my project.
my app is in qt .
i want to make a function that will use a path and return the file info.
but how i do that?

**Comment by JeromeMartinez** [comment]
There are several examples in the [Windows library archive](https://mediaarea.net/download/binary/libmediainfo0/18.05/MediaInfo_DLL_18.05_Windows_x64_WithoutInstaller.7z).
Also available in [Example directory in source code](https://github.com/MediaArea/MediaInfoLib/blob/master/Source/Example/HowToUse_Dll.cpp) ([.h](https://github.com/MediaArea/MediaInfoLib/tree/master/Source/MediaInfoDLL)).
