### ISSUE TITLE
JPEG identified as Gzip

### ISSUE THREAD

**Issue by fraro** [MediaArea/MediaInfo#270]
On Linux, from version 18.x some JPEGs are identified as type "Gzip". Version 17.x is ok.
 
**correct**:
mediainfo --version
MediaInfo Command line, 
MediaInfoLib - v17.12
mediainfo 800x450_cmsv2_f12b5bb1-f480-5303-8d1a-0bd778eafb71-3273014.jpg 
General
Complete name                            : 800x450_cmsv2_f12b5bb1-f480-5303-8d1a-0bd778eafb71-3273014.jpg
Format                                   : JPEG
File size                                : 63.9 KiB

Image
Format                                   : JPEG
Width                                    : 800 pixels
Height                                   : 450 pixels
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Compression mode                         : Lossy
Stream size                              : 63.9 KiB (100%)

**wrong**:
mediainfo --version
MediaInfo Command line, 
MediaInfoLib - v18.05

mediainfo 800x450_cmsv2_f12b5bb1-f480-5303-8d1a-0bd778eafb71-3273014.jpg 
General
Complete name                            : 800x450_cmsv2_f12b5bb1-f480-5303-8d1a-0bd778eafb71-3273014.jpg
Format                                   : GZip
Format profile                           : deflate
File size                                : 63.3 KiB

![800x450_cmsv2_f12b5bb1-f480-5303-8d1a-0bd778eafb71-3273014](https://user-images.githubusercontent.com/9140736/44287388-f4153b80-a26c-11e8-9878-294d7a2d3f7a.jpg)

**Comment by JeromeMartinez** [comment]
the file name of the ticket attachment is "44287388-f4153b80-a26c-11e8-9878-294d7a2d3f7a.jpg", is it the same one as in your example?
I tried on Windows as well as [MediaInfoOnline](https://mediaarea.net/MediaBin/hT9cdoeB) and it is still detected as JPEG.

**Comment by fraro** [comment]
yes, they seem identical, md5 matches ( 150d98150ff03c43a8ace82c20f65264 )
MediaInfoOnline works fine.

**Comment by JeromeMartinez** [comment]
Need more info for reproducing it, I can't also on Linux (CentOS in my case):

```
[~]$ uname -a
Linux sd-100964 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[~]$ wget https://user-images.githubusercontent.com/9140736/44287388-f4153b80-a26c-11e8-9878-294d7a2d3f7a.jpg
Saving to: ‘44287388-f4153b80-a26c-11e8-9878-294d7a2d3f7a.jpg’
[~]$ md5sum 44287388-f4153b80-a26c-11e8-9878-294d7a2d3f7a.jpg
150d98150ff03c43a8ace82c20f65264  44287388-f4153b80-a26c-11e8-9878-294d7a2d3f7a.jpg
[~]$ mediainfo --version
MediaInfo Command line,
MediaInfoLib - v18.05
[~]$ mediainfo "--Inform=General;%Format%" 44287388-f4153b80-a26c-11e8-9878-294d7a2d3f7a.jpg
JPEG
[~]$
```

**Comment by fraro** [comment]
sorry, false alarm! looking on the md5 sums on both systems (with mi 18.x and mi 17.x) shows a different md5. Both files downloaded with wget from same URL, but one seems to have flipping bits. 
Closing.
