### ISSUE TITLE
Lack of information about bitrate of VP9 and Opus streams inside .webm containers

### ISSUE THREAD

**Issue by Nottt** [MediaArea/MediaInfo#271]
You can get a sample from here: https://developers.google.com/media/vp9/settings/vod/

Why I can't see the bitrate of VP9 and Opus streams? 

```
 mediainfo --version
MediaInfo Command line,
MediaInfoLib - v18.05
```

This is messing my tests because I can't know for sure the bit rate of the video :/

**Comment by Nottt** [comment]
I'm using ffmpeg to encode my media with VP9 and Opus. So it seems what I need to do is just remux them to .webm again so the statistic tags will be created?

**Comment by JeromeMartinez** [comment]
FFmpeg does not support statistic tags AFAIK so if you want statistic tags you need to use a tool which embeds them.
This is outside of the scope of MediaInfo, but FYI I think that [mkvpropedit](https://mkvtoolnix.download/doc/mkvpropedit.html) has a `--add-track-statistics-tags` option which may permit to avoid a complete remux (not tested).

**Comment by Nottt** [comment]
I just tested it, it took 12 seconds to do `mkvpropedit --add-track-statistics-tags *webm` with a 5 GB file, I can't know if it's remuxing or not because I have a fast SSD.

I usually use a script to see audio information and it's still not detecting it: 
```
mediainfo "$1" --inform="Audio;Audio: %Language% ID: %ID% Format: %Format% Duration: %Duration/String3% Channels: %Channel(s)% Bitrate: %BitRate/String% Size: %StreamSize/String3% Forced: %Forced% Default: %Default% Delay: %Video_Delay/String%\n"
```

I checked the `--inform parameters` available and doesn't seem to exist any related to the static tags, what do you recommend me to use? The reason I created that script was to avoid printing the entire `mediainfo` output in my terminal, so the ideal solution would be a way to retrieve just what I need instead of running full command.

Thank you!

**Comment by JeromeMartinez** [comment]
> I can't know for sure if it's remuxing or not because I have a fast SSD, but I think it is.

The command appends the tags at the end after having read the whole file, no remux.

> I checked the --inform parameters available and doesn't seem to exist any related to the static tags,

Normal, this is technical, and such tags are just mapped to classic MediaInfo fields (the ones you use in your command). They should be filled with bitrate info now (thanks to statistics tags).

**Comment by Nottt** [comment]
Something is broken then because:

![image](https://user-images.githubusercontent.com/13532436/44576292-8bdec200-a764-11e8-9fa0-37f1f1296a5e.png)

``` 
mediainfo "$1" --inform="Audio;Audio: %Language% ID: %ID% Format: %Format% Duration: %Duration/String3% Channels: %Channel(s)% Bitrate: %BitRate/String% Size: %StreamSize/String3% Forced: %Forced% Default: %Default% Delay: %Video_Delay/String%\n"
```

![image](https://user-images.githubusercontent.com/13532436/44576401-da8c5c00-a764-11e8-84be-e1bea418bfa6.png)

**Comment by JeromeMartinez** [comment]
Oops, I forgot that there is currently an issue in MediaInfo when statistics tags are made after the file muxing (encoding and tagging date don't match, and I put tagging part in different MediaInfo fields).
Related to https://github.com/MediaArea/MediaInfoLib/issues/875.

**Comment by Nottt** [comment]
It happens :)

Is there any workaround?
