### ISSUE TITLE
Bug in View\Custom menu: always selects NISO_Z39.87

### ISSUE THREAD

**Issue by PhilZ-cwm6** [MediaArea/MediaInfo#273]
Hi,

In latest MediaInfo v18.05, when we select "Custom" display in "View" menu, it will always select "NISO_Z39.87"
The only way to fix it is to manually edit **MediaInfo.cfg**:
`Output = Custom`

v18.03.1 and previous have no issues

**Comment by JeromeMartinez** [comment]
Please test [this snapshot](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20180827-4/MediaInfo_GUI_18.05.20180827_Windows.exe), this issue should be fixed but I would like confirmation all is OK.

**Comment by PhilZ-cwm6** [comment]
many thanks for prompt fix
I tested the snapshot, the issue is fixed :-)
Is there some debugging enabled in the snapshot version or can I keep it installed and it will prompt for an update on nexte final release ?

**Comment by JeromeMartinez** [comment]
> it will prompt for an update on nexte final release ?

It should prompt for the update (in few days).

**Comment by JeromeMartinez** [comment]
Fixed by https://github.com/MediaArea/MediaInfo/pull/274.
