### ISSUE TITLE
UWP App Does Not Scale on High DPI

### ISSUE THREAD

**Issue by Xashyar** [MediaArea/MediaInfo#288]
Screen info:
Diagonal: 15.6"
Resolution: 3840 x 2160
Scaling: 250%

### Side to Side Screenshot with the Win32 version:
![image](https://user-images.githubusercontent.com/34171942/46181401-5e8cb300-c2d2-11e8-8398-03a595504205.png)

**Comment by cjee21** [comment]
This issue can be closed. It is outdated. Both current UWP and Win32 (VCL and Qt) GUIs properly support high DPI.

**Comment by Xashyar** [comment]
Thanks  for the update @cjee21 .
