### ISSUE TITLE
REVTMD license

### ISSUE THREAD

**Issue by kieranjol** [MediaArea/MediaInfo#3]
Hello,

I'm curious about the disabling of the REVTMD outout due to non-free licensing. I haven't been able to find any info about that schema's licensing. I saw a reference to the opinion of the FSF in the changelog, but no further info. Is it still restrictive? Seems baffling that the creators wouldn't make it open and free?

Best,

Kieran.

**Comment by JeromeMartinez** [comment]
[REVTMD export code](https://github.com/MediaArea/MediaInfoLib/commit/caeca386704878ae8761b31022a8d3b27f60e8e6) for MediaInfo is under [NASA Open Source Agreement](https://en.wikipedia.org/wiki/NASA_Open_Source_Agreement), which is not approved by e.g. FSF or Debian (see the Wikipedia page for references).
I removed REVTMD when Debian included MediaInfo in their repo and raised the issue.

I wrote the code but I forgot to be precise on the copyright so I can not change the license without the owner agreement, we tried once without being able to go to the end of the change.

That said, my policy now is to own all the code in official MediaInfo release and REVTMD is not highly requested so I did not take the time to eitheir insist for having a CLA from my sponsor or code it again.
