### ISSUE TITLE
Doesn't load new file when dragged and dropped from different drive

### ISSUE THREAD

**Issue by vertigo220** [MediaArea/MediaInfo#300]
I recently started experiencing an issue where when I open MediaInfo for a file via the context menu, then drag another file into it, it only updates/loads the new file if it's from the same drive. If the second file is on a different drive, it does nothing. I'm running the latest version (18.08.1) and have tried uninstalling and reinstalling it. I'm using Win10 x64.

**Comment by cjee21** [comment]
Unable to reproduce with MediaInfo 24.12 (both VCL and Qt GUI) on Windows 11.
