### ISSUE TITLE
possible to have more metadata about .srt files in mediainfo ?

### ISSUE THREAD

**Issue by shirishag75** [MediaArea/MediaInfo#307]
Currently while parsing a subtitle file (an .srt) get only the following  info. - 
```

$ mediainfo abcd.srt
General
Complete name                            : abcd.srt
Format                                   : SubRip
File size                                : 94.6 KiB

Text
Format                                   : SubRip
Compression mode                         : Lossless
```

It would be a marked improvement if we can get the fps of an srt, would make it easier for rsyncing purposes. 

```
Package: mediainfo
Version: 18.08.1-1
Severity: normal


-- System Information:
Debian Release: buster/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'unstable-debug'), (500, 'testing-debug'), (500, 'unstable'), (1, 'experimental-debug'), (1, 'experimental')
Architecture: amd64 (x86_64)

Kernel: Linux 4.18.0-2-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages mediainfo depends on:
ii  libc6            2.27-8
ii  libgcc1          1:8.2.0-9
ii  libmediainfo0v5  18.08.1-1
ii  libstdc++6       8.2.0-9
ii  libzen0v5        0.4.37-1

mediainfo recommends no packages.

Versions of packages mediainfo suggests:
pn  mediainfo-gui  <none>

-- no debconf information
```

**Comment by JeromeMartinez** [comment]
> It would be a marked improvement if we can get the fps of an srt,

SRT has absolutely no "FPS" stuff.
Example:

> 00:00:30,800 --> 00:00:34,000

This is in milliseconds.

> would make it easier for rsyncing purposes.

As there is also no total duration (you get only the end timestamp of the last "frame"), you can also not rely on any duration.

***

The only solution for automatic sync of SRT with audio is to have analysis of the audio content, detection about when people speak. Is doable with modern technology, but with different tools (and I don't know enough about them).
