### ISSUE TITLE
--ExternalMetadata=...

### ISSUE THREAD

**Issue by csisanyi** [MediaArea/MediaInfo#308]
I would like to add additional metadata with Mediainfo to EBUCore output (ex. comments, keywords, tags...).

In MediaInfo/History_CLI.txt i found that it might be possible
Version 18.03, 2018-03-19
--------------
+ EBUCore: possibility to inject external metadata in the output from MediaInfo

I have checked the manual and it says:
--ExternalMetadata=...
                    Add external metadata to the output (EBUCore output)
--ExternalMetadataConfig=...
                    Output template for external metadata (EBUCore output)

Could someone please help me how to use the --ExternalMetadata option
For example, I'm creating an EBUCore log file, how can I add my own custom EBU tags to the output?
I'm receiving the following error message any time I use the --ExternalMetadata option

E: Invalid column size for external metadata

~$ mediainfo --Output=EBUCore --LogFile=ebulog.txt --ExternalMetadata=anything SampleVideo.mp4 

Do I need to add a String with my tags, or an external file?

Thanks in advance.

**Comment by JeromeMartinez** [comment]
This feature was developed for specific needs for a specific customer, doc was not sponsored so here is a quick and dirty example:

template.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<ebucore:ebuCoreMain xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:ebucore="urn:ebu:metadata-schema:ebucore" xmlns:xalan="http://xml.apache.org/xalan" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ebu:metadata-schema:ebucore https://www.ebu.ch/metadata/schemas/EBUCore/20171009/ebucore.xsd" version="1.8" writingLibraryName="MediaInfoLib" writingLibraryVersion="18.03.1" dateLastModified="2018-11-20" timeLastModified="10:32:46Z">
<ebucore:coreMetadata>
<!-- title -->
<ebucore:title>
<dc:title>%Title%</dc:title>
</ebucore:title>
<!--MediaInfo-->
<ebucore:format/>
</ebucore:coreMetadata>
</ebucore:ebuCoreMain>
```

data.csv
```
Filename;Title
1.tif;CustomTitle
2.tif;AnotherCustomTitle
```

command:
```
.\MediaInfo.exe %%f --Output=EBUCore --ExternalMetadata=file://data.csv --ExternalMetadataConfig=file://template.xml >%%f.EBUCore.xml
```

If you would like to sponsor better documentation, please [contact us](https://mediaarea.net/Contact).
