### ISSUE TITLE
Cannot build on Ubuntu

### ISSUE THREAD

**Issue by gmparker2000** [MediaArea/MediaInfo#309]
I followed the readme instructions carefully.  

- apt-get install git automake autoconf libtool pkg-config make g++ zlib1g-dev
- downloaded 18.04 amd64 deb files from https://mediaarea.net/fr/MediaInfo/Download/Ubuntu
- dpkg -i libmediainfo* libzen*
 - cloned the project
- ./autogen.sh
- ./configure --enable-shared

I get the following error from configure:

./configure: line 15849: libzen-config: command not found
configure: error: libzen configuration is not found

Help

**Comment by g-maxime** [comment]
You have the -dev packages installed for libmediainfo and libzen?
pkg-config --list-all list them?

**Comment by gmparker2000** [comment]
Ah - no I missed that subtle part about the dev packages.  I installed them and all is well.  Thanks.
