### ISSUE TITLE
mediainfo crash

### ISSUE THREAD

**Issue by shirepirate** [MediaArea/MediaInfo#31]
program version: MediaInfo_GUI_0.7.83_Windows.exe
OS version: Microsoft Windows 10 Enterprise 64-bit (10.0.10586)

issue:
MediaInfo constantly crashes. Sometimes, upon system restart, it will work for 30 seconds before crashing. After this, any launch of the program will result in an immediate crash (whether starting the executable or starting from the context menu of a media file). I have reinstalled the application several times. The only window displayed is this:

![mwsnap005 2016-03-13 21_14_07](https://cloud.githubusercontent.com/assets/2275004/13732834/89e8fd72-e960-11e5-8d9c-9a86da9d0fab.png)

Compatibility modes in Windows do not fix this issue. Running the program as administrator does not fix this issue.

I can't find a crash log in MediaInfo's program folder and don't know how to debug it. From the symptoms it seems like conflict with another program, but I have no way of knowing what application that could be. I do have Corsair Link, MSI Afterburner & D3DGear installed, as well as Nvidia Graphics Drivers and the Geforce Experience software.

**Comment by shirepirate** [comment]
this has not been fixed with v0.7.84

still crashes extremely often whenever opened. any way to trace?

**Comment by JeromeMartinez** [comment]
For the moment, I don't have more reports about stability issues like this one, looks like "local" to this machine, so I (the main developer) don't plan to debug it for the moment.
In case there are more people with this issue, I'll implement some debug functionalities (there is nothing for debugging such random crash for the moment)
