### ISSUE TITLE
qt version can't show info for files opened from context menu

### ISSUE THREAD

**Issue by Digitalone1** [MediaArea/MediaInfo#321]
Hello, I installed mediainfo qt version on my Arch Linux because gtk version looks ugly and was not showing correctly on my system. 

Installed if from here: https://aur.archlinux.org/packages/mediainfo-gui-git
Here are commands for building: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mediainfo-gui-git

qt version looks good, I start the app, open a media file and it works, but the only issue is that I cannot open a file from context menu. When I do it, the gui is like this: 

![image](https://user-images.githubusercontent.com/25790525/52227968-61676800-28b1-11e9-9dd3-a77f973e2c2e.png)

Desktop entry is:
> [Desktop Entry]
> Type=Application
> Version=1.0
> Name=MediaInfo
> Comment=Supplies technical and tag information about a video or audio file
> Comment[fr]=fournit des informations techniques et les tags à propos de vos fichiers video et audio
> Icon=mediainfo
> Exec=mediainfo-gui %f
> Terminal=false
> MimeType=video/mpeg;video/x-mpeg;video/msvideo;video/quicktime;video/x-anim;video/x-avi;video/x-ms-asf;video/x-ms-wmv;video/x-msvideo;video/x-nsv;video/x-flc;video/x-fli;video/x-flv;video/vnd.rn-realvideo;video/mp4;video/mp4v-es;video/mp2t;application/ogg;application/x-ogg;video/x-ogm+ogg;audio/x-vorbis+ogg;application/x-matroska;audio/x-matroska;video/x-matroska;video/webm;audio/webm;audio/x-mp3;audio/x-mpeg;audio/mpeg;audio/x-wav;audio/x-mpegurl;audio/x-scpls;audio/x-m4a;audio/x-ms-asf;audio/x-ms-asx;audio/x-ms-wax;application/vnd.rn-realmedia;audio/x-real-audio;audio/x-pn-realaudio;application/x-flac;audio/x-flac;application/x-shockwave-flash;audio/vnd.rn-realaudio;audio/x-pn-aiff;audio/x-pn-au;audio/x-pn-wav;audio/x-pn-windows-acm;application/x-extension-mp4;audio/mp4;audio/amr;audio/amr-wb;application/x-shorten;audio/x-ape;audio/x-wavpack;audio/x-tta;audio/x-opus+ogg;
> Categories=AudioVideo;AudioVideoEditing;
> Keywords=media info;metadata;tag;video;audio;subtitles;chapters;codec;mkv;mpeg;mp3;h264;avc;h265;hevc;avi;

As you can see, `%f` in exec line should be enough to pass file location as argument to the application, but it won't work. Tried also to switch to `%u` and `%n`, but nothing changes. That's weird since gtk version is exactly the same exec line and it works.

If I write `mediainfo-gui "full/path/to/filename"` from command line, it works correcty.

Any tips to fix? Thanks.

**Comment by g-maxime** [comment]
Cannot reproduce on Fedora/Gnome (using the same .desktop file)

What file browser do you use?

**Comment by Digitalone1** [comment]
I use Dolphin on Plasma 5.

This is GTK version opened from  context menù.

![migtk_mod](https://user-images.githubusercontent.com/25790525/52268264-5e18be80-293b-11e9-9e8e-4b07e894f54f.png)

This Qt opened inside the app.

![miqt_mod](https://user-images.githubusercontent.com/25790525/52268299-78eb3300-293b-11e9-9a39-cbc82708ffcf.png)

Qt looks a lot better.

Anyway, I tried opening from context menu in Dolphin with both versions and only GTK works. Don't know why. Any hint to try to figure out what's going wrong with Qt?

**Comment by g-maxime** [comment]
You can try with the latest master

#322

**Comment by Digitalone1** [comment]
Thank you, it's working now.
