### ISSUE TITLE
text in square brackets stripped in $if() section

### ISSUE THREAD

**Issue by vpil** [MediaArea/MediaInfo#339]
I run:
`mediainfo --Output=file://params.txt  video.mkv`

params.txt:
`General;%Movie%\n$if(%Movie%,%Movie%\n)`

Bad output:
```
test title [2019]
test title
```

**Comment by JeromeMartinez** [comment]
In next version or [nightlies](https://mediaarea.net/download/snapshots/binary/) tomorrow.
