### ISSUE TITLE
Adjust font size in Text view (Mac)

### ISSUE THREAD

**Issue by fcccbf8f8f1** [MediaArea/MediaInfo#346]
Is there any way to adjust/increase the font size for "View - Text"? On a Mac (v19.04) it is VERY tiny, around 8, and nearly impossible to read without zooming in.

**Comment by JeromeMartinez** [comment]
This is currently not possible, but planned.

**Comment by swrobel** [comment]
Any update on the plans? It's nearly unreadable on high-rez screens like my Macbook Pro 14"

**Comment by JeromeMartinez** [comment]
Just to be sure we talk about the same thing, do you speak about the Mac App Store version or the free old version?

**Comment by swrobel** [comment]
@JeromeMartinez installed via homebrew

<img width="262" alt="Screenshot 2024-02-07 at 9 58 50 AM" src="https://github.com/MediaArea/MediaInfo/assets/157270/f4697578-e2ed-4e01-b6de-14701989a993">

**Comment by JeromeMartinez** [comment]
This one is less priority because it is less integrated with the OS compared to the Mac App Store version but we'll have a quick look if it is quick to implement.

**Comment by swrobel** [comment]
Ok, thanks, I wasn't aware of the appstore version, and it's a huge improvement in readability, even if the font size still isn't adjustable.

**Comment by JeromeMartinez** [comment]
[development snapshot](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20240213/MediaInfo_GUI_24.01.20240213_Mac.dmg) with the option for font size for the free version.
