### ISSUE TITLE
Bug in parsing AVID VC-3 parsing (File_Vc3::CodingControlB())

### ISSUE THREAD

**Issue by go4shoe** [MediaArea/MediaInfo#362]
MediaInfoLib\Source\MediaInfo\Video\File_Vc3.cpp Line 854
File_Vc3::CodingControlB()

    Info_SB(   FFE,                                             "FFE, Field/Frame Count"); Param_Info1(Vc3_FFE[FFE]);
    Get_SB (   SSC,                                             "SSC, Sub Sampling Control"); Param_Info1(Vc3_SSC[SSC]);
    Mark_0();
    Mark_0();
    Get_S1 (2, CLV,                                             "CLR, Color Volume"); Param_Info1(Vc3_CLV[CLV]);
    Get_SB (   CLF,                                             "CLF, Color Format"); Param_Info1(Vc3_CLF[CLF]);

In the above code reads only 1 bit for SSC but the field is actually two bits. See SMPTE ST 2019-1:2016; 7.2.5  Coding Control B.

**Comment by JeromeMartinez** [comment]
Thanks for the tip, looks like there was a typo during implementation of 2016 version, as all other parts of the related code seem fine.
You can test with [snapshots](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/) (20190626 minimum).
Note: I don't have 4:2:0 streams, would be great if you can provide one for our automatic tests.

Please prefer https://github.com/MediaArea/MediaInfoLib/issues for issues related to file formats.

**Comment by go4shoe** [comment]
Jerome, 
thanks for the quick response and fix. Unfortunately - I can't make 4:2:0 files since we haven't wired up 4:2:0. Currently we support 4:4:4(:4) and 4:2:2.
Sorry!
