### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by watchmon** [MediaArea/MediaInfo#379]
use libmediainfo-dev build an example with valgrind find memory leak
![image](https://user-images.githubusercontent.com/1973283/64619935-83136980-d415-11e9-8ae9-9556af61e039.png)
how to fix it?

**Comment by JeromeMartinez** [comment]
> build an example

Please more details about how to reproduce this example.
If I remember well last time we tested [our example](https://github.com/MediaArea/MediaInfoLib/blob/master/Source/Example/HowToUse_Dll.cpp) it was fine with Valgrind.

**Comment by watchmon** [comment]
I build an example on my ubuntu server(18.04.2)，source code below
![image](https://user-images.githubusercontent.com/1973283/64664431-cd323480-d481-11e9-857a-6248bcc06d90.png)
I use apt-get install libmediainfo-dev,I don`t know the so library no version info.
![image](https://user-images.githubusercontent.com/1973283/64664610-429e0500-d482-11e9-953b-5fc69df930d7.png)

**Comment by watchmon** [comment]
the default libmediainfo-dev version is 17.02, I update to 19.07,  also has memoryleak, did I use the wrong API?

**Comment by watchmon** [comment]
more leak infomation
![image](https://user-images.githubusercontent.com/1973283/64672884-5015b800-d49f-11e9-9392-c1e99d7380f3.png)

**Comment by JeromeMartinez** [comment]
We use to test with the `wchar_t` version, we missed the leak with the `char` version.
[Fixed](https://github.com/MediaArea/MediaInfoLib/pull/1170/files), in public version next month (too late for the release of today).
