### ISSUE TITLE
[Feature Request] Full HD aspect

### ISSUE THREAD

**Issue by ticao2** [MediaArea/MediaInfo#390]
[Feature Request] Full HD aspect
Inform in pixel how an image will look when displayed on a Full HD (1080x1920) screen.
For example, a 640 x 480 movie should display at 1440 x 1080 pixels.
Or a 1280 x 546 movie should display at 1920 x 819 pixels.

**Comment by ticao2** [comment]
Is there any chance that my feature will be implemented?
Or should I forget about this?

**Comment by JeromeMartinez** [comment]
Sorry not to have answered, a lot late on all the answers I have to provide.
It could be interesting to add, but it would not be by default because it is redundant information (it would be in "advanced mode" and for customized output).
Priority of features depends on the votes of [MediaArea members](https://mediaarea.net/SupportUs).
I added [an entry to the list of features](https://mediaarea.net/Vote/Full-Hd-Aspect-197).

**Comment by ticao2** [comment]
Thank you very much for your prompt reply.
My language is not English, so everything is translated by Google Translate. :-)
If I understand correctly, this information still does not exist.
It doesn't make sense for me to try the functions that are in **Video**, between **Width** and **ActiveFormatDescription_M**.
Therefore, I must do the calculations myself to get this information.
But if and when it exists, this information must be in **"advanced mode"** and for customized output.
If I understand wrong, please correct me.
Thank you.

**Comment by JeromeMartinez** [comment]
> If I understand correctly, this information still does not exist.

The exact information you want doe not exist yet, but you have all you need for computing how it would be displayed on your screen based on your screen characteristic (here we don't talk anymore of information from the file).

> It doesn't make sense for me to try the functions that are in Video, between Width and ActiveFormatDescription_M.

`ActiveFormatDescription` is not related to your request, as it is a dedicated metadata transported by some streams only.

> Therefore, I must do the calculations myself to get this information.

For the moment: yes. Relatively easy.
the computing would be based on `Width`, `Height` and `PixelAspectRatio`.
In your examples `PixelAspectRatio` is usually 1.000, so let's give maths in that case (you need to adapt formulas for the case `PixelAspectRatio` is not 1.000):
Display aspect ratio of your screen is 1.778.
if `Width`/`Height` is less than 1.778, your height will be 1080 and your width will be 1080*(`Width`/`Height`).
if `Width`/`Height` is more than 1.778, your width will be 1920 and your height will be 1920/(`Width`/`Height`).

> But if and when it exists, this information must be in "advanced mode" and for customized output.

it is not "must", it is just an arbitrary (based on good reasons) choice from me.

**Comment by ticao2** [comment]
Thank you one more time.
