### ISSUE TITLE
Translation Toolkit

### ISSUE THREAD

**Issue by stevenlele** [MediaArea/MediaInfo#419]
When I was translating (#418), I did some research and wrote some translation notes.

After that, I wrote a toolkit which can help other translators work more efficiently.

This includes scripts to convert the language file into a spreadsheet file in their target language, together with adding comments and notes.

Please put this toolkit somewhere to help the other translators.

~~[mediainfo_translation_toolkit.zip](https://github.com/MediaArea/MediaInfo/files/4265120/mediainfo_translation_toolkit.zip)~~

~~[mediainfo_translation_toolkit.zip](https://github.com/MediaArea/MediaInfo/files/4271369/mediainfo_translation_toolkit.zip)~~ (Update on Mar 1, 2020: Fix bug)

[mediainfo_translation_toolkit.zip](https://github.com/MediaArea/MediaInfo/files/4271380/mediainfo_translation_toolkit.zip) (Update on Mar 1, 2020: add note to "at ... fps")

Please read `readme.md` for instructions.

**Comment by JeromeMartinez** [comment]
@stevenlele would you mind to open a PR with this files in e.g. `/Contrib/mediainfo_translation_toolkit`?

**Comment by stevenlele** [comment]
@JeromeMartinez OK.
