### ISSUE TITLE
detect bad frames, mp3?

### ISSUE THREAD

**Issue by atomGit** [MediaArea/MediaInfo#425]
mp3info has an option to detect "bad" frames - i'm not sure how it's doing that, but looking at the source i see in mp3_frame_header.cpp...

```C
void mp3_frame_header::SetFrameHeader(char* pMemory)
{
    m_FrameHeader=((unsigned char)pMemory[0] << 24)|((unsigned char)pMemory[1] << 16)|((unsigned char)pMemory[2] << 8)|(unsigned char)pMemory[3];
}

//! \brief Test if a frame header it is a true frame header.
/*!
    \return If is valid return true else false.
*/
bool mp3_frame_header::IsValidFrameHeader(void) const
{ 
    if(((m_FrameHeader&FRAME_SYNC) == FRAME_SYNC) && 
        (GetMPEGVersion() != INVALID_MPEG) && 
        (GetLayerVersion() != INVALID_LAYER) &&
        (GetBitrate() != INVALID_BITRATE) &&
        (GetBitrate() != FREE_BITRATE) &&
        (GetSamplerate() != INVALID_SAMPLERATE)) 
        return(true); 
    return(false); 
}
```

i'm wondering if a similar capability can be added to mediainfo?

**Comment by JeromeMartinez** [comment]
>  i'm not sure how it's doing that, 

Not difficult to implement, I actually have something similar for just ignoring the frame.

> i'm wondering if a similar capability can be added to mediainfo?

MediaInfo is more a metadata reporter, not a conformance checker (we have [MediaConch](https://mediaarea.net/MediaConch) for that, and I wonder how to report that (MediaInfo shows a global view of the file, not a frame by frame reporting). And also it would be more a "sync lost" heck than a "bad frame".
How useful would it be a single test i.e. not a complete MP3 conformance checker?
So how would you see the corresponding output?

Note: I am aware I already have some conformance checking features in MediaInfo, but at some point I need to think about how to avoid a "it does all but all not so well" piece of software.

**Comment by atomGit** [comment]
i saw MediaConch before and it didn't seem to be an efficient choice for use with mp3s, however i think maybe ffmpeg already does what i need when it decodes

at any rate, i was looking to eliminate a dependency on mp3info but i like that it's able to clearly inform of the count of frames and count of bad frames rather then just detecting a decoding error

i understand if you don't wish to add such functionality in which case i'll let it up to you to close the ticket
