### ISSUE TITLE
Can no longer access s3 object with 20.03 via libcurl and presigned URL

### ISSUE THREAD

**Issue by dylan60420** [MediaArea/MediaInfo#446]
in v19.09, i could/can run 'mediainfo "$(aws s3 presign s3://bucket/object)"' and receive expected metadata. in v20.03, about 'Access Denied'. I have tried this on multiple EC2 instances running Linux2 installed with yum from the EPEL repo, and my laptop macOS with mediainfo installed by brew. I have downloaded/compiled/installed the source for 19.09 on the EC2s, and the above command works as expected. I have also manually installed 20.03 from source on the EC2s, and it yields the same result as the install from yum. 

Full error message:
mediainfo --output=JSON "$(aws s3 presign s3://bucket/object)"
E: https://redacted.s3.us-east-2.amazonaws.com/redacted?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=redactedt&X-Amz-Date=20200426T041925Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=redacted, <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>redacted</RequestId><HostId>redacted</HostId></Error>

**Comment by JeromeMartinez** [comment]
[Fixed](https://github.com/MediaArea/MediaInfoLib/issues/221), [snapshots](https://mediaarea.net/download/snapshots/binary/) should be fine.
