### ISSUE TITLE
Add repository for Ubuntu arm64 (raspberry pi 4)

### ISSUE THREAD

**Issue by notDavid** [MediaArea/MediaInfo#448]
Hi there,

Since there is now an [official Ubuntu 64-bit 19.10 and 20.04 image for the Raspberry Pi](https://ubuntu.com/download/raspberry-pi), please consider adding a repository for it to https://mediaarea.net/en/Repos#deb

Thank you!

```
$ wget https://mediaarea.net/repo/deb/repo-mediaarea_1.0-12_all.deb && dpkg -i repo-mediaarea_1.0-12_all.deb && apt-get update
--2020-05-01 18:07:40--  https://mediaarea.net/repo/deb/repo-mediaarea_1.0-12_all.deb
Resolving mediaarea.net (mediaarea.net)... 217.182.128.108, 2001:41d0:401:3100::6bc7
Connecting to mediaarea.net (mediaarea.net)|217.182.128.108|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4782 (4.7K) [application/x-debian-package]
Saving to: ‘repo-mediaarea_1.0-12_all.deb’

repo-mediaarea_1.0-12_all.deb   100%[=======================================================>]   4.67K  --.-KB/s    in 0.001s

2020-05-01 18:07:40 (8.06 MB/s) - ‘repo-mediaarea_1.0-12_all.deb’ saved [4782/4782]

Selecting previously unselected package repo-mediaarea.
(Reading database ... 112596 files and directories currently installed.)
Preparing to unpack repo-mediaarea_1.0-12_all.deb ...
Unpacking repo-mediaarea (1.0-12) ...
Setting up repo-mediaarea (1.0-12) ...
Hit:1 http://ports.ubuntu.com/ubuntu-ports eoan InRelease
Get:2 http://ports.ubuntu.com/ubuntu-ports eoan-updates InRelease [97.5 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports eoan-backports InRelease [88.8 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports eoan-security InRelease [97.5 kB]
Ign:5 https://mediaarea.net/repo/deb/ubuntu eoan InRelease
Get:6 https://mediaarea.net/repo/deb/ubuntu eoan Release [2,615 B]
Get:7 https://mediaarea.net/repo/deb/ubuntu eoan Release.gpg [836 B]
Fetched 341 kB in 2s (170 kB/s)
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://mediaarea.net/repo/deb/ubuntu eoan In
Release' doesn't support architecture 'arm64'

$ uname -a
Linux pi4 5.3.0-1023-raspi2 #25-Ubuntu SMP Tue Apr 14 11:35:19 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Ubuntu 19.10"
```

**Comment by JeromeMartinez** [comment]
For our Linux builds we rely on [Open Build Service](https://build.opensuse.org). Fortunately they have an instance of `arm7l` (for Ubuntu Pi 32-bit) and `aarch64` (for Ubuntu Pi 64-bit), [I tested for ZenLib](https://build.opensuse.org/package/binaries/home:MediaArea_net:snapshots/ZenLib/xUbuntu_20.04).

If I am OK for adding both Pi versions for Ubuntu 20.04 in addition the x86_64, less motivated for Ubuntu 19.10 (not LTS, it will be end of life not in 3 months).

If the build from Open Build Service is compatible (I read `arm64` for the arch, Open Build Service has `aarch64` target).

**Comment by JeromeMartinez** [comment]
Development snapshots have 32- and 64-bit ARM packages for Ubuntu 20.04, please test [our snapshots repos](https://mediaarea.net/Repos).

**Comment by notDavid** [comment]
@JeromeMartinez Just tested and i can confirm it's working for me on a Rpi4 running Ubuntu 20.04 LTS 64-bit 👌🏼

**Comment by notDavid** [comment]
@JeromeMartinez FYI: should the commands with `_1.0-12_all.deb` be changed to `_1.0-13_all.deb` on https://mediaarea.net/en/Repos#deb ?

**Comment by JeromeMartinez** [comment]
> should the commands with _1.0-12_all.deb be changed to _1.0-13_all.deb on https://mediaarea.net/en/Repos#deb ?

Oops, the [corresponding patch was merged days ago](https://github.com/MediaArea/MediaArea-Website/pull/329) but I forgot to click on "deploy" somewhere... Done.

**Comment by notDavid** [comment]
😁👍🏼

**Comment by fryfrog** [comment]
@JeromeMartinez, what would it take to get these into *non* snapshots?

https://mediaarea.net/repo/deb/ubuntu/pool/focal-snapshots/main/m/mediainfo/

vs

https://mediaarea.net/repo/deb/ubuntu/pool/focal/main/m/mediainfo/

**Comment by JeromeMartinez** [comment]
A public release :).
(coming soon)
