### ISSUE TITLE
mp4: add MLP/TrueHD audio detection

### ISSUE THREAD

**Issue by Nomis101** [MediaArea/MediaInfo#451]
According to ​http://mp4ra.org/#/codecs TrueHD in MP4 has the codec name mlpa. FFmpeg added experimental support for muxing Dolby TrueHD streams to movenc here: ​http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=808a6717e0c584738c60a109afd6d47f4973d619
This PDF describes "Dolby TrueHD (MLP) bitstreams within the ISO base media file format" ​https://developer.dolby.com/globalassets/technology/dolby-truehd/dolbytruehdbitstreamswithintheisobasemediafileformat.pdf
VLC added support here. https://github.com/videolan/vlc/commit/9c49f401aecbc86ceea08bfadfb8e83ac0340590

It would be nice, if MediaInfo could also properly detect such audio streams. Currently it looks like this:

```
Audio #1
ID                                       : 2
Format                                   : mlpa
Codec-ID                                 : mlpa
Dauer                                    : 1min 2s
Bitrate                                  : 4 806 Kbps
Stream-Größe                             : 36,0 MiB (13%)
Titel                                    : Surround
Default                                  : Ja
Alternate group                          : 1
Kodierungs-Datum                         : UTC 2020-05-09 10:36:27
Tagging-Datum                            : UTC 2020-05-09 10:36:27
```

**Comment by JeromeMartinez** [comment]
Is it possible to have a sample file? (only need few milliseconds).

**Comment by Nomis101** [comment]
Hope that helps.
[sample.zip](https://github.com/MediaArea/MediaInfo/files/4603432/sample.zip)
