### ISSUE TITLE
S3 Signed URL not working with Inform parameter

### ISSUE THREAD

**Issue by JesseDode** [MediaArea/MediaInfo#454]
I've been running into an issue with using presigned S3 url's and using the `Inform` command. I'm running 

20.03
```
mediainfo --urlencode --Inform='Video;%Width%' 'https://bucket.s3.us-west-2.amazonaws.com/file.mp4?X-Amz-Algorithm=XXXX&X-Amz-Credential=XXX&X-Amz-Date=XXX&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Security-Token=XXX&X-Amz-Signature=XXX'
```

Pre-20.03
```
mediainfo --Inform='Video;%Width%' 'https://bucket.s3.us-west-2.amazonaws.com/file.mp4?X-Amz-Algorithm=XXXX&X-Amz-Credential=XXX&X-Amz-Date=XXX&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Security-Token=XXX&X-Amz-Signature=XXX'
```

Each of those commands return an output like
```
E: https://bucket.s3.us-west-2.amazonaws.com/file.mp4?X-Amz-Algorithm=XXXX&X-Amz-Credential=XXX&X-Amz-Date=XXX&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Security-Token=XXX&X-Amz-Signature=XXX, HTTP server doesn't seem to support byte ranges. Cannot resume.
854
```

The interesting thing is that after the error, it's returning the desired value from the `--Inform` flag. Getting the full mediainfo output from the s3Url's is working fine, regardless of the version. This has been apart of a workflow for some time, and we've recently started seeing this issue. 

I've tested this on version 20.03, 19.09,18.12, 17.12, and snapshot 20200523. It's running in a Ubuntu 18.04 docker image.

**Comment by JeromeMartinez** [comment]
> The interesting thing is that after the error, it's returning the desired value from the --Inform flag. 

It is because we don't need the content after the seek for the width, it is usually at the beginning.

Workaround: if I remember well we output errors to stderr and result to stdout so you can filter.

With some formats, we seek in the file. I am surprised that byte ranges are not supported.
Please drop me an URL (with a couple of days of lifetime) at my email address so I can check myself.

**Comment by JesseDode** [comment]
Here's a dockerfile that emulates our process

```
# First we need to build gpac to get a standalone mp4box binary

FROM buildpack-deps:bionic

ENV TMPDIR=/var/tmp \
    MEDIAINFO_VERSION=20.03 \
    LIBZEN_VERSION=0.4.38
WORKDIR /app

# Now we can actually fetch all the dependencies for the Genie Worker
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        software-properties-common \
        curl \
        tar \
        libcurl3-gnutls \
        libmms0 \
        python3-distutils \
        rsync \
        cron \
        tree \
        imagemagick \
        openssh-client \
        apt-transport-https \
        wget \
        unzip \
        apt-utils \
        openjdk-8-jre-headless \
    && rm -rf /var/lib/apt/lists/*

# Mediainfo
RUN wget https://mediaarea.net/download/binary/libzen0/${LIBZEN_VERSION}/libzen0v5_${LIBZEN_VERSION}-1_amd64.xUbuntu_18.04.deb && \
    wget https://mediaarea.net/download/binary/libmediainfo0/${MEDIAINFO_VERSION}/libmediainfo0v5_${MEDIAINFO_VERSION}-1_amd64.xUbuntu_18.04.deb && \
    wget https://mediaarea.net/download/binary/mediainfo/${MEDIAINFO_VERSION}/mediainfo_${MEDIAINFO_VERSION}-1_amd64.xUbuntu_18.04.deb && \
    dpkg -i libzen0v5_${LIBZEN_VERSION}-1_amd64.xUbuntu_18.04.deb && \
    dpkg -i libmediainfo0v5_${MEDIAINFO_VERSION}-1_amd64.xUbuntu_18.04.deb && \
    dpkg -i mediainfo_${MEDIAINFO_VERSION}-1_amd64.xUbuntu_18.04.deb && \
    rm *.deb
```

**Comment by djeikyb** [comment]
which release will this be in?

**Comment by JeromeMartinez** [comment]
> which release will this be in?

In the next one, this month, in the meanwhile you can use the previous version 19.09 or [development snapshots](https://mediaarea.net/download/snapshots/binary/).
