### ISSUE TITLE
5.1 opus audio being reported as 6 channel

### ISSUE THREAD

**Issue by paradox460** [MediaArea/MediaInfo#461]
I have a file that has 5.1 opus audio in it. `ffprobe` reports it as having only 5.1, but `mediainfo` reports it as having 6.

Here's the audio output of mediainfo on this file
```
Audio
ID                                       : 2
Format                                   : Opus
Codec ID                                 : A_OPUS
Duration                                 : 23 min 40 s
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Rear: L R, LFE
Sampling rate                            : 48.0 kHz
Bit depth                                : 32 bits
Compression mode                         : Lossy
Title                                    : English
Writing library                          : Lavc58.54.100 libopus
Language                                 : English
Default                                  : No
Forced                                   : No
Statistics Tags Issue                    : mkvmerge v46.0.0 ('No Deeper Escape') 64-bit 2020-05-30 13:56:23 / Lavf58.29.100
FromStats_BitRate                        : 256000
FromStats_Duration                       : 00:23:40.776000000
FromStats_FrameCount                     : 44399
FromStats_StreamSize                     : 45464576
```

| | |
|-|-|
| OS | Ubuntu 18.04.4 LTS |
| Mediainfo version | MediaInfoLib - v17.12 |

**Comment by JeromeMartinez** [comment]
> 5.1 opus audio being reported as 6 channel

Well, in practice a 5.1 content has 6 channels...
Issue is that a third party software says "6.0" when doing the difference between non-LFE and LFE channels, checking a file I tried to create from FFmpeg it seems that the LFE channel is not correctly handled (non-LFE vs LFE is in anotehr field, and hidden one)

```
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Rear: L R, LFE
Channel positions                        : 3/2/1
```

should be :
```
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Rear: L R, LFE
Channel positions                        : 3/2/0.1
```

We need to check the code in order to understand why the LFE is not indicated as such in the third line.

**Comment by paradox460** [comment]
For full disclosure, the reencoding was encoded via `ffmpeg -i <omitted> -c copy -c:a libopus -af  aformat=channel_layouts="5.1" <omitted>`

The ffmpeg docs for `aformat` and `channel-layout` indicate that there's another version, called `5.1(side)`. It appears to be the same as the `5.1` layout though

**Comment by JeromeMartinez** [comment]
> [...] there's another version, called 5.1(side). It appears to be the same as the 5.1 layout though

There is 2 layout names in FFmpeg for a reason: they are not same.
In FFmpeg:
`5.1` si for "L R C Lb Rb LFE" layout, i.e. "rear" scheme
`5.1(side)` is for "L R C Ls Rs LFE" layout, i.e. "side" a.k.a. "surround" scheme
You can learn more on channel layout on [MediaArea Audio Channel Layout](https://mediaarea.net/AudioChannelLayout) page.

FYI `5.1(side)` Layout is not supported by Opus.
