### ISSUE TITLE
MediaInfo 64-bit and MediaInfo DLL

### ISSUE THREAD

**Issue by Bamajon1974** [MediaArea/MediaInfo#463]
When MediaInfo Universal Installer (32/64-bit) or MediaInfo 64-bit without Installer is installed, task manager shows a 32-bit version running. Why does this happen? 

Are there instructions to install and use the MediaInfo.dll file? 

Thanks!

**Comment by JeromeMartinez** [comment]
> When MediaInfo Universal Installer (32/64-bit) or MediaInfo 64-bit without Installer is installed, task manager shows a 32-bit version running. Why does this happen?

For the moment the GUI is still 32-bit, the package contains 32-bit and 64-bit DLL for Windows Explorer integration. It will change in the future.

> Are there instructions to install and use the MediaInfo.dll file?

Not really, but the ZIP DLL package on [The Windows download page](https://mediaarea.net/en/MediaInfo/Download/Windows) contains examples for lot of programming languages.

**Comment by Bamajon1974** [comment]
Understood. What is the standalone DLL file used for? Does it need a front end, such as the GUI, to be functional? Or can it be copied into a Windows/System directory, registered with REGSVR command and used to generate information through File Explorer?

**Comment by JeromeMartinez** [comment]
> registered with REGSVR command and used to generate information through File Explorer?

In the case of the GUI package, the 64-bit DLL is used in 64-bit Windows for Windows Explorer integration (can be activated in the GUI in preferences).

It is also usable by any third party software willing to use the DLL (Filebot etc)

**Comment by Bamajon1974** [comment]
Ok. So the DLL file needs an accompanying GUI to be used, correct? It cannot be used by itself?

**Comment by JeromeMartinez** [comment]
> It cannot be used by itself?

Last L in "DLL" means "Library"...

> So the DLL file needs an accompanying GUI to be used

...Or a command line interface, or anything able to call a DLL.

**Comment by Bamajon1974** [comment]
Got it. Thank you for your help!
