### ISSUE TITLE
MediaInfo crashes on MacOS (MPEG-H 3D Audio)

### ISSUE THREAD

**Issue by Dniel97** [MediaArea/MediaInfo#471]
Hello,
I'm using the MacAppStore Version of MediaInfo 20.03 and I own a MPEG-H 3D Audio file which is embedded in MPEG-4 container, but every time I want to open the file, MediaInfo crashes. I'm not allowed to upload the file public, so if anyone wants to test this I can provide the audio file. This is the crash log from MacOS: [https://pastebin.com/51rrX6vR](https://pastebin.com/51rrX6vR)

**Comment by JeromeMartinez** [comment]
Should be resolved with new version 20.08.
