### ISSUE TITLE
‘Segmentation fault (core dumped)’ on some Matroskas, running in Ubuntu headless

### ISSUE THREAD

**Issue by stephenmcconnachie** [MediaArea/MediaInfo#480]
At the BFI National Archive, we’re seeing a new error in our MediaInfo CLI use – a reproducible ‘Segmentation fault (core dumped)’ for many – but not all - FFV1 Matroskas that we have created using FFMPEG.

We have used the CLI to generate reports for thousands of these FFV1 MKVs and only recently encountered this issue. It is not filesize based, as it is reproducible with small files <1GB and huge files at 200GB.

We use the MediaInfo CLI in various Ubuntu headless hosts and the one where we are seeing this, is running an old version, so that is possibly the cause. I will test it in a newer Ubuntu version and confirm the behaviour on these same files.

I will post download links to two of the files where the Segmentation fault error is 100% reproducible.

Notes:
- we can use ffprobe on the files without issue so read from path is not an issue
- we can change filename for the files in their path, using 'mv' in same terminal and path, so general share / folder permissions is not an issue
- all files in the folder have same permissions, and we confirmed with chown to same user:group
- we can use MediaInfo GUI from a Windows machine to report on the files

So it is only CLI. File download links to follow.

All the best, Stephen McCOnnachie, BFI National Archive

**Comment by JeromeMartinez** [comment]
>  is running an old version,

please test with [the latest snapshot of libmediainfo](https://mediaarea.net/download/snapshots/binary/libmediainfo0/), so we are sure it is not already fixed.

**Comment by stephenmcconnachie** [comment]
I will. Also I just tested it on a newer version of Ubuntu on a larger server (RAM and CPU) and it could not be reproduced. So it may be old Ubuntu and weak server...

**Comment by stephenmcconnachie** [comment]
Actually I'll deploy our Media Info workflow to the newer Ubuntu machine, and get the problem machine up to a newer version, I don't want to waste your time with old Ubuntu version issues.

**Comment by JeromeMartinez** [comment]
MediaInfo does not consume much RAM (else this is a bug), I guess it is due to the newer MediaInfo version.
We currently don't support backporting such fix, except if there is a big need to have the exact same version.

In the meanwhile I see 

>  I don't want to waste your time with old Ubuntu version issues.

:-D.

**Comment by stephenmcconnachie** [comment]
Weirdly, it is the same MediaInfo version (19.09) on each machine. I will blame the old Ubuntu and take this as a prompt to get up to date.
