### ISSUE TITLE
Reading this TS file is causing MediaInfo to crash, the DLL throws a SystemAccessViolation causing the parent to also crash

### ISSUE THREAD

**Issue by rboy1** [MediaArea/MediaInfo#487]
When trying to read this file: https://www.dropbox.com/s/5d4ir8riltbb18w/Burgers%2C.Brew.%26.Que.S03E08.Beers%2C.Burgers.and.Bocce.in.Baltimore.ts?dl=0

MediaInfo crashes. While the GUI version throws an exception, the DLL version causes much more serious issues, it throws a System.AccessViolationException (corruption in protected memory) which also causes the calling (.NET) application to crash since managed code cannot handle System.AccessViolationException in .NET in a try catch block.

![image](https://user-images.githubusercontent.com/3846367/94075171-b29ad700-fdc8-11ea-8862-3b5c24834859.png)

**Comment by JeromeMartinez** [comment]
Fix will be in next release, and also in the next [dev snapshots](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/).
