### ISSUE TITLE
Broadcast Wave version

### ISSUE THREAD

**Issue by thorsted** [MediaArea/MediaInfo#493]
MediaInfo does not seem to report BText version.

**Comment by JeromeMartinez** [comment]
MediaInfo is more general purpose than e.g. [BWF MetaEdit](https://MediaArea.net/BWFMetaEdit), we have internally in MediaInfo the `bext` version in order to parse the `bext` fields specific to a version, but we don't show it, true.

So it is more a matter of policy about what to show in MediaInfo rather than a technical issue.
I need to be convinced that such info in MediaInfo output would be useful to most MediaInfo users e.g. that there is an important interoperability issue with some tools (which ones?) if the version is not supported, in the meanwhile [BWF MetaEdit](https://MediaArea.net/BWFMetaEdit) can provide this piece of information.

**Comment by thorsted** [comment]
Jerome,

Thanks for the explanation. Many people use the MediaInfo tool for extracting Metadata from A/V files prior to permanent archiving and having as much technical metadata extracted for discovery and risk analysis is important. We have thought about adding BWF MetaEdit is as another extractor, but more convenient to have one extractor (MediaInfo) for many formats.

**Comment by JeromeMartinez** [comment]
How `bext` version is important to know before permanent archiving? Issue here is that if I export everything each person wants because it is important for this person, the MediaInfo output would have hundreds of lines, so I need to filter output requests, and I filter from how it is important for e.g. interoperability.
@dericed @kmurmur any thoughts?

**Comment by kmurmur** [comment]
Hi @JeromeMartinez  - not exactly sure what you mean about bext version. do you mean bwf version? sorry to misunderstand

**Comment by JeromeMartinez** [comment]
@kmurmur right, `bext` is the ["Broadcast Audio Extension Chunk"](https://tech.ebu.ch/docs/tech/tech3285.pdf) identifier of the dedicated chunk found in BWF files, and indicates BWF version used.

**Comment by kmurmur** [comment]
ah right - got it. so each version is slightly different from the one before (obviously). you can infer the version if so example theres loudness, its v2

**Comment by dericed** [comment]
With mkv, in the generic, default mediainfo output "Format version" is there. Doesn't seem unreasonable to also reveal the value for BWF.

**Comment by JeromeMartinez** [comment]
My concern is about if it is really useful to overload the MediaInfo output with the version of BWF, knowing that if loudness is present I show it (so if BWF fields used in a specific are used, it is easy to guess the BWF version used).

**Comment by dericed** [comment]
Hmm, from a user perspective I would presume that the behavior be the step, that if Format version is shown for one format, then it's absence for another means that either it is not semantically understood by mediainfolib or non-existant in the file.
On the other hand, if I was using mediainfo in an archival workflow where this information mattered, I wouldn't be using the default mediainfo output.

**Comment by JeromeMartinez** [comment]
> With mkv, in the generic, default mediainfo output "Format version" is there. Doesn't seem unreasonable to also reveal the value for BWF.

BWF is "just" a way for people to say that it is a WAV (the real format) file with some specific metadata which has no impact on the content decoding itself. It is more a metadata version, so in reality it is not a format version, so my concern to overload the output. "Marketing" vs reality.
In theory (not the case with WAV as WAV has no version) I would have a format version and a metadata X version and a metadata Y (`bext` chunk is one chunk possible, but the file could also contain metadata from another spec) version and so on.
Is there known interoperability issues with different BWF metadata versions?

**Comment by kmurmur** [comment]
i'd also say that you'd have to know that the loudness is the defining feature of v2.

**Comment by JeromeMartinez** [comment]
> On the other hand, if I was using mediainfo in an archival workflow where this information mattered, I wouldn't be using the default mediainfo output.

An intermediate solution is to put the BWF version in the advanced text output / XML / JSON, but not in the default output. It is already done for lot of other MediaInfo output fields.

**Comment by kmurmur** [comment]
@JeromeMartinez I don't know of interop issues but maybe? I'm thinking it would be best to declare the version to eliminate the issue (there's v0, 1 and 2): From our fdds: "There have been three iterations of the BWF format under the general specification number EBU Tech 3285. Version 0 (as it came to be called) was published in 1997. Version 1, which differs from Version 0 in the use of 64 of the 254 reserved bytes to contain a SMPTE UMID identifier, was published July 2001. Version 1 was followed by six supplements with additional information. Version 2 references these supplements and adds elements that pertain to loudness metadata."

**Comment by dericed** [comment]
I don't think there's any interoperability beyond the potential for using loudness data. I suppose here I'd suggest Format version with verbose output (-f), otherwise omit to be concise.
