### ISSUE TITLE
"Sheet" UI elements should allow resizing and moving.

### ISSUE THREAD

**Issue by OneOfMany07** [MediaArea/MediaInfo#500]
New user again.  I was surprised by the UI I see when picking "Sheet".  I have a large empty, white space where the filename is listed at the top (is a little more than half the window).  Then 5 lines (only 4 with values), then a larger text area at the bottom about the same size as the 5 lines.  That area at the bottom has a scroll bar, so I assumed I could drag the top line of that pane and it would get bigger.  Using up that wasted white space at the top.  But nope...I must scroll the 6 or so lines of text I can see if I want to know more of what the bottom pane has.

Seems like a waste of screen real estate currently, but maybe I don't know the purpose of that page?

And why can't I change the size of these elements?  I recognize the 5 lines with "web" buttons to the right probably won't change size, but they should move.

**Comment by royalef** [comment]
I'm glad to see I'm not the only one who sees this and thinks "hunh?"

I have assumed that this was a pure bug or just an abandoned, not fully developed feature.  Just upgraded and see nothing changed.  At full screen, the silliness is magnified. (below)

![mediainfo-fullscreenSHEET](https://user-images.githubusercontent.com/33466635/112991767-7eb4bb80-9135-11eb-937c-4cdea7fb8a64.JPG)
