### ISSUE TITLE
[Bug] Random missing informations with some storage class in S3

### ISSUE THREAD

**Issue by flibustier** [MediaArea/MediaInfo#504]
Hello @JeromeMartinez  !

We got some issues with `mediainfo` since about beginning of october, using https url from S3
Here a fresh example with a TS file, in some cases we got this result (format is `AVC` instead of `MPEG-TS` for example) :
```
"track": [
            {
                "@type": "General",
                "VideoCount": "1",
                "FileExtension": "ts",
                "Format": "AVC",
                "FileSize": "1383872324",
                "FrameRate": "25.000",
                "extra": {
                    "FileExtension_Invalid": "avc h264 264"
                }
            },
…
```
And sometime we got normal result :
```
"track": [
            {
                "@type": "General",
                "ID": "1",
                "VideoCount": "1",
                "AudioCount": "1",
                "FileExtension": "ts",
                "Format": "MPEG-TS",
                "FileSize": "1383872324",
                "Duration": "697.989132593",
                "OverallBitRate_Mode": "CBR",
                "OverallBitRate": "15861000",
                "FrameRate": "25.000",
                "FrameCount": "17399",
                "extra": {
                    "OverallBitRate_Precision_Min": "15860989",
                    "OverallBitRate_Precision_Max": "15861011"
                }
            },
            {
```
MediaInfo version doesn’t seems to be related, neither OS (we got this result with 20.03 on linux and 20.08/09 on mac os)

We notice that if copy this file with a different storage class (from Standard to Intelligent-Tiering) is seems to work everytime

Do you have an idea of what could be involve ?

(I can provide you some presign url in PM)

**Comment by JeromeMartinez** [comment]
It seems that the TS is not detected so fallback on the AVC found in the file. Weird if the file is wealthy.
Please send an example by PM.
