### ISSUE TITLE
GPG key is expired for SLES 15 (15.1, 15.2) with repo 1.0-13

### ISSUE THREAD

**Issue by gildas** [MediaArea/MediaInfo#506]
Hi,

Installed the repo via rpm:
```console
rpm -Uvh https://mediaarea.net/repo/rpm/releases/repo-MediaArea-1.0-13.noarch.rpm
```

Then refreshed the repositories via `zypper refresh`, and SLES complains loudly as the GPG Key is expired:

```
Retrieving repository 'MediaArea.net SARL software repository for rpm based distributions - x86_64' metadata [....                                                                                                     

Automatically importing the following key:

  Repository:       MediaArea.net SARL software repository for rpm based distributions - x86_64
  Key Name:         MediaArea <info@mediaarea.net>                                              
  Key Fingerprint:  C5CDF62C 7AE05CC8 47657390 C10E1109 0EC0E438                               
  Key Created:      Mon 23 Jan 2017 03:34:34 PM UTC                                             
  Key Expires:      Thu 23 Jan 2020 03:34:34 PM UTC (EXPIRED)                                  
  Subkey:           63316BDB0E2D2918 2017-01-23 [expired: 2020-01-23]                          
  Rpm Name:         gpg-pubkey-0ec0e438-5886228a                                                


Warning: The gpg key signing file 'repomd.xml' has expired.
  Repository:       MediaArea.net SARL software repository for rpm based distributions - x86_64
  Key Name:         MediaArea <info@mediaarea.net>                                              
  Key Fingerprint:  C5CDF62C 7AE05CC8 47657390 C10E1109 0EC0E438                               
  Key Created:      Mon 23 Jan 2017 03:34:34 PM UTC                                             
  Key Expires:      Thu 23 Jan 2020 03:34:34 PM UTC (EXPIRED)                                  
  Subkey:           63316BDB0E2D2918 2017-01-23 [expired: 2020-01-23]                          
  Rpm Name:         gpg-pubkey-0ec0e438-5886228a                                                
Signature verification failed for file 'repomd.xml' from repository 'MediaArea.net SARL software repository for rpm based distributions - x86_64'.

    Note: Signing data enables the recipient to verify that no modifications occurred after the data
    were signed. Accepting data with no, wrong or unknown signature can lead to a corrupted system
    and in extreme cases even to a system compromise. 

    Note: File 'repomd.xml' is the repositories master index file. It ensures the integrity of the
    whole repo.

    Warning: This file was modified after it has been signed. This may have been a malicious change,
    so it might not be trustworthy anymore! You should not continue unless you know it's safe.

Signature verification failed for file 'repomd.xml' from repository 'MediaArea.net SARL software repository for rpm based distributions - x86_64'. Continue? [yes/no] (no): no
error]
Repository 'MediaArea.net SARL software repository for rpm based distributions - x86_64' is invalid.
[MediaArea|https://mediaarea.net/repo/rpm/releases/SLE_15/x86_64] Valid metadata not found at specified URL 
Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'MediaArea.net SARL software repository for rpm based distributions - x86_64' because of the above error.
```

**Comment by JeromeMartinez** [comment]
We updated the key, should be OK now.

what is the content of your /etc/os-release ?
the SLE_15 repo is no more updated, we update the 15.1 (and soon we'll provide a 15.2 repo) only (something we should maybe avoid and keep "15" everywhere...) and our script should detect your 15.1 and redirect to 15.1 repo.

**Comment by gildas** [comment]
Thanks @JeromeMartinez,

Well the content of /etc/os-release will change depending on the SLES version. I tried all 3 of them (15, 15.1, and 15.2).
I use the SLES JEOS version for OpenStack, so it's pretty clean.

I don't know if final customers must upgrade their 15.0 to 15.1, but what if they don't have to and they don't do it. I don't know SUSE's policy in that regards. All I know is SLES 15's EOL is 2028/07/31. The EOL of each SP (¨SP0¨ as well) is not clear to me.
Which is why I test of all 3.

This is the /etc/os-release on SLES 15:
```
NAME="SLES"
VERSION="15"
VERSION_ID="15"
PRETTY_NAME="SUSE Linux Enterprise Server 15"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15"
```

And this is the /etc/os-release on SLES 15.1:
```
NAME="SLES"
VERSION="15-SP1"
VERSION_ID="15.1"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP1"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp1"
```

Finally, /etc/os-release on SLES 15.2:
```
NAME="SLES"
VERSION="15-SP2"
VERSION_ID="15.2"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp2"
```

**Comment by JeromeMartinez** [comment]
>  I tried all 3 of them (15, 15.1, and 15.2).

So that explains why we saw SLE_15, ok.

> I don't know if final customers must upgrade their 15.0 to 15.1

They must, if I understand well [SLE Product Life Cycle](https://documentation.suse.com/sles/15-SP1/html/SLES-all/cha-upgrade-background.html#sec-upgrade-background-life-cycle) ("SUSE supports previous service packs for six months after the release of the new service pack").

I did not find info about binary compatibility, and actually I wonder if it is worth it to have a MediaInfo dedicated repo for each SP.

> but what if they don't have to and they don't do it.

The old GPG key was an issue, which is fixed. So they'll get a version of MediaInfo having the same age as their distro end of life. Our build farm provider ([OBS](https://build.opensuse.org/)) still provides older SP but I am not sure I want to compile for unmaintained (at least in default support, I read that SUSE provides an option long term support of few years) versions of SLE.

**Comment by gildas** [comment]
Yeah, I agree with you, no need to continue to upgrade/maintain your software on 15.0
As long as the GPG key is good (as you fixed it), yeah, they would get an outdated version of mediainfo. But same with everything else they would get for 15.0. When they upgrade to 15.1, they would get something more up-to-date, unitl 15.1 is end of support. 
That is very fine with me. If our customers are not, well, that's their problem and they should talk to SUSE...

I will run some quick tests on each version to see if I get mediainfo installed.
I also understand I should wait for 15.2 as you guys are not ready yet. No biggie. I can wait a couple of weeks.
