### ISSUE TITLE
MediaInfo v20.09: Bug compare view

### ISSUE THREAD

**Issue by WernerBleisteiner** [MediaArea/MediaInfo#510]
When you have files in the compare view and change their order, not all data fields get transported correctly!
This leads to wrong display of attributes - and thus misinterpretation and mis-conclusions
Watch the attached video and look closely what happens to the data in the audio segment.

[sc-Mediainfo-Compare-bug-when-exchanging.mov.zip](https://github.com/MediaArea/MediaInfo/files/5637376/sc-Mediainfo-Compare-bug-when-exchanging.mov.zip)

**Comment by JeromeMartinez** [comment]
There is definitely a big issue with the column reordering, we fix that soon.

**Comment by WernerBleisteiner** [comment]
Thanks🙏🏻
