### ISSUE TITLE
FAQ: "No GUI for Linux" is outdated

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaInfo#52]
The [MediaInfo FAQ page](https://mediaarea.net/en/MediaInfo/Support/FAQ#GUI_Linux) seems to be outdated, regarding that there is no GUI for Linux:

> **Why isn't there a GUI version of MediaInfo for Linux?**
> VCL (the graphical library of Borland) is not portable (this is the only one), so I can't adapt the GUI for Linux.
> If you know how to program with wxWidgets (a standard graphical library), and are interested in adapting MediaInfo to wxWidgets, then I am interested. Please contact me!

**Comment by GuillaumeRoques** [comment]
Thanks, it have been fix : https://github.com/MediaArea/MediaArea-Website/pull/34
