### ISSUE TITLE
Shows wrong FPS for NTSC DVD (calculates FPS after IVTC)

### ISSUE THREAD

**Issue by pcroland** [MediaArea/MediaInfo#522]
nevermind, it's a soft-telecined DVD

**Comment by JeromeMartinez** [comment]
> Scan order                               : 2:3 Pulldown

The mention of fake `30000/1001` is there.
The choice in MediaInfo is to show the real frame rate (and progressive) + indication that players not supporting 24/1.001 would play it at 24/1.001*5/2/2=30/1.001 (and interlaced)
See [2:3 Pulldown](https://en.wikipedia.org/wiki/Three-two_pull_down#2:3).

> shows the correct 29.97 fps.

It is not correct, it is a legacy mode for tools not supporting IVTC.
It is a choice from FFmpeg not to show 24/1.001 despite they detect it is progressive, I don't know why.

**Comment by JeromeMartinez** [comment]
> nevermind, it's a soft-telecined DVD

Too late :).

**Comment by ValZapod** [comment]
> they detect it is progressive, I don't know why

Because a movie can have a soft telecine, hard telecine and interlaced and even cadences of more complexity in the stream.
