### ISSUE TITLE
MIXML: https to XSD might be a problem

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaInfo#53]
There are https:// links pointing to the (not yet existing) XSD file for the future MediaInfo XML schema definition.

This might cause a problem for validating applications, since not all of them are to be expected to support HTTPS.

**Comment by JeromeMartinez** [comment]
> (not yet existing)

Not yet existing? Not normal! I'll check!

> This might cause a problem for validating applications, since not all of them are to be expected to support HTTPS.

I don't like the idea to avoid a secure connection because of old tools. unfortunately, I can not say "https if possible, fallback on http for legacy apps".

**Comment by pjotrek-b** [comment]
XSD link in MIXML just brings me to the MediaInfo home page:
https://mediaarea.net/mediainfo/mediainfo_2_0.xsd

I agree with the fact that it's bad to go for insecure, just because "it's easier" - but in the case of a schema definition, I'm not sure if the benefit of https is really of significance - considering the possible fault cases it brings...

I was just mentioning this, because I got a "protocol not supported" in an XML Editor, when I wanted to validate the XML ;)

**Comment by JeromeMartinez** [comment]
> XSD link in MIXML just brings me to the MediaInfo home page:

Will fix it. In the meanwhile you can download it here:
https://github.com/MediaArea/MediaAreaXml/blob/master/mediainfo.xsd

> I agree with the fact that it's bad to go for insecure, just because "it's easier" - but in the case of a schema definition, I'm not sure if the benefit of https is really of significance - considering the possible fault cases it brings...

Issue with "HTTPS only when it is important" is that it provides information about content of HTTPS ("ho, you use HTTPS, so it is important for you"), this is the reason lot of people want HTTPS everywhere.
Thing e.g. HTTP/2 with non-secure connections not supported at all in Firefox and Chrome.
This may also be a good excuse for trying to motivate XML editor developers to add HTTS support in their tool.

> I was just mentioning this, because I got a "protocol not supported" in an XML Editor, when I wanted to validate the XML ;)

May be a good feature request for this XML editor ;-).
More seriously, this is a subject that is very close to my heart so I am not willing to "revert" that without a super good reason and without possibility to do manner.
Would an option e.g. --no-https (not the default) satisfy everybody?

**Comment by pjotrek-b** [comment]
I absolutely agree with you, that encryption should become a common thing these days. And not the exception.

If it's not too much hassle, I think the option "--no-https" (as **non** default) is a good compromise.

**Comment by pjotrek-b** [comment]
btw: Just encountered that "xmllint" also can't do https :disappointed:

**Comment by JeromeMartinez** [comment]
`--https=0`  (you can also use `--no-https`) options are added in MediaInfo CLI 0.7.86 as well as MediaConch CLI 16.05 just released.

**Comment by pjotrek-b** [comment]
Thanks a lot! :)
