### ISSUE TITLE
GPac failed several versions

### ISSUE THREAD

**Issue by githubReneFischer** [MediaArea/MediaInfo#536]
[logs.zip](https://0x0.st/-Twr.zip)

**Comment by JeromeMartinez** [comment]
Please more details about what you think is wrong with MediaInfo, and A/V files (logs from third party tools are not useful for MediaInfo).

**Comment by githubReneFischer** [comment]
Dear Jerome, I am very sorry wanting to post this on the media-autobuild-suite (mas) and gone ultimately wrong. Mediainfo is a wonderful and versatile tool I also build with that and works perfectly - no issues.
If for a feature request I would have only one plea: having mediainfo interpret aac headers (aac, libfdk_aac) but that is a completely different story. Cheers Rene

**Comment by JeromeMartinez** [comment]
> having mediainfo interpret aac headers (aac, libfdk_aac) 

Please a dedicated ticket (preferably on https://github.com/MediaArea/MediaInfoLib/issues) with more details.
