### ISSUE TITLE
Show ElementShow from Subtitle Track

### ISSUE THREAD

**Issue by kkm** [MediaArea/MediaInfo#545]
I dont understand, sometimes "ElementCount" like " Count of Elements" doesnt always show

![image](https://user-images.githubusercontent.com/134290/123541205-8dfed180-d743-11eb-89bd-8733483fa0ec.png)

**Comment by JeromeMartinez** [comment]
We rely on [Track statistics tags](https://gitlab.com/mbunkus/mkvtoolnix/-/wikis/Track-statistics-tags) for providing such information. If such metadata does not exist, it is not provided (we don't scan the full file, only method for retrieving such info when the muxer does not write it).

**Comment by kkm** [comment]
that means old MKV has to re-encode again?

**Comment by JeromeMartinez** [comment]
No need to do anything, it is just informational metadata and does not hurt to not have it.
If you want to add such metadata, no need to re-encode or remux, just add the corresponding metadata at the end of the file, with e.g. "[mkvpropedit](https://mkvtoolnix.download/doc/mkvpropedit.html) --add-track-statistics-tags".

**Comment by kkm** [comment]
I didnt know about this command from you. So I learned something from you.

mkvpropedit --add-track-statistics-tags old.mkv is better than mkvmerge -o new.mkv old.mkv
