### ISSUE TITLE
Comment not displayed when it's added by exiftool

### ISSUE THREAD

**Issue by superbonaci** [MediaArea/MediaInfo#548]
Download any YouTube video:
````
youtube-dl -f mp4 --add-metadata https://www.youtube.com/watch?v=6stlCkUDG_s -o download.mp4
````

Then add the `URL` as `Comment`:
````
exiftool.exe -Comment='https://www.youtube.com/watch?v=6stlCkUDG_s' download.mp4
    1 image files updated
````

Open `download.mp4` and `Comment` doesn't appear.

**Comment by cjee21** [comment]
Unable to reproduce with exiftool 12.89 and MediaInfo 24.11 on mp4 file. The comment added by exiftool is visible in MediaInfo.

**Comment by superbonaci** [comment]
Thanks probably has been fixed.
