### ISSUE TITLE
will not cross-compile using gcc 11.2

### ISSUE THREAD

**Issue by hydra3333** [MediaArea/MediaInfo#551]
Have you tried building with gcc 11.2 ?

it aborts with some sort of overload issue around ?zenlib?
although it builds fine under gcc 10.3.0

I could spend an hour re-doing it and generating a log if you need one.

**Comment by hydra3333** [comment]
For clarity, it was cross-compiling on host ubuntu/mingw64 for target Windows 10 x64.

**Comment by JeromeMartinez** [comment]
[tentative of fix](https://github.com/MediaArea/ZenLib/pull/133/files).

**Comment by hydra3333** [comment]
Oops, this is with mediainfolib ... I'll post an issue over there ... in summary:
No, it isn't resolved.
Cross-compiling under Ubuntux64/mingw64, with target Win10 x64.
With an identical build system, it cross-compiles OK under gcc 10.3.0 however it fails under gcc 11.2.0.

**Comment by LigH-de** [comment]
see: https://github.com/MediaArea/MediaInfoLib/issues/1449
