### ISSUE TITLE
Wrong media info of certain jpegs

### ISSUE THREAD

**Issue by richardnoya** [MediaArea/MediaInfo#553]
I have a file, that is actually too big too upload (13,1 MB) of which the metadata are:
Format: JPEG
Width: 3680 px
Height: 2418 px
Color Space: YUVK
Chroma subsampling: 4:4:4
Bit depth: 8 bits
Compression mode: Lossy
Color space_ICC: CMYK

But the webversion (https://mediaarea.net/MediaInfoOnline as well as version 21.03 we use in our application) reports:
General
Complete name                            : boat.jpg
Format                                   : MPEG Audio
File size                                : 13.1 MiB
Overall bit rate mode                    : Variable
FileExtension_Invalid                    : m1a mpa mpa1 mp1 m2a mpa2 mp2 mp3

Audio
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 1
Format settings                          : Intensity Stereo / 50/15ms
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Sampling rate                            : 32.0 kHz
Compression mode                         : Lossy
Stream size                              : 13.1 MiB (100%)

Do you understand what's going wrong here?

If you need the image I could provide a URL to it.

Regards Richard.

**Comment by JeromeMartinez** [comment]
MediaInfo library issue, so https://github.com/MediaArea/MediaInfo/issues/553 is prefered.
