### ISSUE TITLE
Some audio streams have codec ID "lpcm" while others have "in24" but are the same in ffprobe

### ISSUE THREAD

**Issue by iamdamosuzuki** [MediaArea/MediaInfo#557]
I have two files that were created using two different Black Magic applications. One was created with Media Express (ME) and the other with Resolve (R). 

The audio stream in the ME file reports as "in24"

```
Audio
ID                                       : 2
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : in24
Duration                                 : 1 h 0 min
Source duration                          : 1 h 0 min
Bit rate mode                            : Constant
Bit rate                                 : 2 304 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Bit depth                                : 24 bits
Stream size                              : 1 003 MiB (1%)
Source stream size                       : 1 003 MiB (1%)
Language                                 : English
Encoded date                             : UTC 2021-08-16 21:42:30
Tagged date                              : UTC 2021-08-16 21:42:30
```

The audio stream in R file reports as "lpcm"

```
Audio #1
ID                                       : 2
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : lpcm
Duration                                 : 1 h 32 min
Bit rate mode                            : Constant
Bit rate                                 : 1 152 kb/s
Channel(s)                               : 1 channel
Channel layout                           : C
Sampling rate                            : 48.0 kHz
Bit depth                                : 24 bits
Stream size                              : 766 MiB (1%)
Default                                  : Yes
Alternate group                          : 1
Encoded date                             : UTC 2021-09-02 23:07:18
Tagged date                              : UTC 2021-09-02 23:07:18
```

However, ffprobe reports these streams as essentially identical (minus the number of channels in the stream)

Here's the ME file:

`Stream #0:1(eng): Audio: pcm_s24le (in24 / 0x34326E69), 48000 Hz, 2 channels, s32 (24 bit), 2304 kb/s (default)`

Here's the R file:

` Stream #0:1: Audio: pcm_s24le (in24 / 0x34326E69), 48000 Hz, 4.0, s32 (24 bit), 4608 kb/s (default)`

Is there an actual difference here? Is it worthwhile to distinguish the two for quality control purposes? Thanks!

**Comment by kieranjol** [comment]
I know very little about this stuff, but isn’t in24 big endian? This
outdated Ffmpeg issue has some
Interesting info
http://trac.ffmpeg.org/ticket/1881

K

**Comment by JeromeMartinez** [comment]
> However, ffprobe reports these streams as essentially identical (minus the number of channels in the stream)

And MediaInfo seems to say that too:

```
Format                                   : PCM
Format settings                          : Little / Signed
```

> Is there an actual difference here?

The CodecID used

>  Is it worthwhile to distinguish the two for quality control purposes? Thanks!

Not for quality, but for interoperability (some players may understand "in24" and not "lpcm" CodecIDs/4CC, or the vice versa)

**Comment by JeromeMartinez** [comment]
> I know very little about this stuff, but isn’t in24 big endian?

From your link ;-) "'in24' samples are Big Endian, unless there is the 'enda' atom present".
We handle 'enda' atom.

**Comment by iamdamosuzuki** [comment]
Thanks for this info! I assume it's safe to close this topic since there's not really a problem with mediainfo in this case, correct?
