### ISSUE TITLE
Multi audios Language info get none

### ISSUE THREAD

**Issue by skyunix** [MediaArea/MediaInfo#568]
if the media have multi audios 
CLI use `Language/String`  some of language will be none

**Comment by Marvll** [comment]
> Please provide a use case (sample file and command you try).

i find that some of the media audio `Language` was none , just  `Title` .

**Comment by JeromeMartinez** [comment]
It is fine with the multi-audio files we have. Without a sample file demonstrating the issue we can't debug.
