### ISSUE TITLE
E-AC-3 JOC not returning "JOC" when using --inform

### ISSUE THREAD

**Issue by jwsmite** [MediaArea/MediaInfo#574]
I have a DD+ Atmos file which returns "Format : E-AC-3 JOC" with default usage `mediainfo inputfile.ec3`. The same file when used with:
`mediainfo --inform="Audio;%Format%" inputfile.ec3` just responds "E-AC-3". Test file I used was from : [Dolby online delivery test files](https://ott.dolby.com/OnDelKits/DDP/Dolby_Digital_Plus_Online_Delivery_Kit_v1.4.1/Test_Signals/elementary_streams/Elementary_Streams.html)

**Comment by JeromeMartinez** [comment]
"Format : E-AC-3 JOC" is the "nice" string displayed to UI users.
For automation, use either "%Format/String%" (the displayed string) or more detailed "%Format%" + "%Format_AdditionalFeatures%" (because JOC is actually an additional feature of E-AC-3, E-AC-3 is still the main format used).

**Comment by jwsmite** [comment]
I can get the string response I need now for my script thanks. The full usage is: 
`mediainfo --inform="Audio;%Format/String%" inputfile.ec3` for my use case.
