### ISSUE TITLE
Mediainfo CPU-loop-crashes on 48kHz/32 float (f32l) WAVs

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaInfo#580]
Hello! :smile:

I've tried opening WAV files created with most recent Audacity (v3.1.2) with MediaInfo (v21.09-1). GUI as well as Commandline:
Mediainfo GUI freezes, process simply hangs like forever, using CPU but doesn't seem to transfer any data from disk/network. :confused:

OS is Xubuntu Focal 21.04.3 (64bit).
Files open fine in, e.g. Audacity and VLC and ffplay.

**ffprobe says:**

> Input #0, wav, from '1-seite_a.wav':
>   Metadata:
>     title           : 1-seite_a
>     date            : 2021
>     track           : 1
>   Duration: 00:47:12.12, bitrate: 3072 kb/s
>     Stream #0:0: Audio: pcm_f32le ([3][0][0][0] / 0x0003), 48000 Hz, 2 channels, flt, 3072

I'd like to attach the Mediainfo report, but, well... I can't ;) ---  :stuck_out_tongue_winking_eye: :grin:

**Comment by JeromeMartinez** [comment]
[Fixed](https://github.com/MediaArea/MediaInfoLib/pull/1440), in [snapshots](https://mediaarea.net/download/snapshots/binary/).

**Comment by pjotrek-b** [comment]
wow! :astonished: :sunglasses:

How'd you do that? Had you already fixed it, or was this the quickest patch ever? :grin:

Thanks and have a nice evening!

**Comment by JeromeMartinez** [comment]
"on Oct 3" :).
I need to do a release soon...

**Comment by robUx4** [comment]
> "on Oct 3" :). 
> I need to do a release soon...

Yes, I got hit with the same bug.
