### ISSUE TITLE
VP9 Profile 2 support

### ISSUE THREAD

**Issue by almirus** [MediaArea/MediaInfo#584]
Hi! please add support vp9.2 and hdr10+ metadata
<details>

D:\ffmpeg>ffprobe.exe "HDR10+_Sample_Video.webm"                                                                     ffprobe version 4.4.1-essentials_build-www.gyan.dev Copyright (c) 2007-2021 the FFmpeg developers                                           built with gcc 11.2.0 (Rev1, Built by MSYS2 project)                                                                                      configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband                                                    libavutil      56. 70.100 / 56. 70.100                                                                                                    libavcodec     58.134.100 / 58.134.100                                                                                                    libavformat    58. 76.100 / 58. 76.100                                                                                                    libavdevice    58. 13.100 / 58. 13.100                                                                                                    libavfilter     7.110.100 /  7.110.100                                                                                                    libswscale      5.  9.100 /  5.  9.100                                                                                                    libswresample   3.  9.100 /  3.  9.100                                                                                                    libpostproc    55.  9.100 / 55.  9.100                                                                                                  Input #0, matroska,webm, from 'HDR10+_Sample_Video.webm':                                                                                   Metadata:                                                                                                                                   encoder         : google/video-file                                                                                                     Duration: 00:00:12.48, start: 0.000000, bitrate: 4129 kb/s                                                                                Stream #0:0(eng): Video: vp9 (Profile 2), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 1920x1080, SAR 1:1 DAR 16:9, 29.97 fps, 29.97 tbr, 1k tbn, 1k tbc (default)                                                                                                                     Side data:                                                                                                                                  Content Light Level Metadata, MaxCLL=1000, MaxFALL=200                                                                                    Mastering Display Metadata, has_primaries:1 has_luminance:1 r(0.1500,0.0600) g(0.6800,0.3200) b(0.2650 0.6900) wp(0.3127, 0.3290) min_luminance=0.005000, max_luminance=1000.000000          

</details>

[HDR10+_Sample_Video.webm.zip]https://github.com/MediaArea/MediaInfo/files/7779402/HDR10%2B_Sample_Video.webm.zip)

**Comment by ValZapod** [comment]
Just for the reference ffprobe -show_frames will show HDR10+ metadata.

**Comment by almirus** [comment]
@JeromeMartinez It’s working as it should now.
