### ISSUE TITLE
Repository unusable

### ISSUE THREAD

**Issue by SSoft7** [MediaArea/MediaInfo#585]
Hi,

I can't update

`wget https://mediaarea.net/repo/deb/repo-mediaarea_1.0-19_all.deb && dpkg -i repo-mediaarea_1.0-19_all.deb && apt-get update
`

> Err:8 https://mediaarea.net/repo/deb/ubuntu focal InRelease
>   403  Forbidden [IP: 139.99.40.229 443]
> 
> 

Same issue with Ubuntu Bionic

**Comment by JeromeMartinez** [comment]
Issue during server migration, we are on it.

**Comment by JeromeMartinez** [comment]
Back online.
