### ISSUE TITLE
"Unable to write to output file" should return non-zero exit code

### ISSUE THREAD

**Issue by plondino** [MediaArea/MediaInfo#588]
Currently, if you provide an invalid path for an output file, MediaConch CLI prints an error but returns a zero exit code, making using the CLI in a script more difficult:

```
C:\tools\MediaConchCLI\mediaconch --Policy=C:\code\python\pymediaconch\pymediaconch\tests\mediaconch_policy_smptett.xml C:\code\python\pymediaconch\pymediaconch\tests\..\..\policies\sources\Warner_Media_OTT_2025973_BatmanBegins_BRP_Full_SUBTITLE.xml --output-xml=/Downloads/result.xml
Unable to write to output file: /Downloads/result.xml
(dev39) PS C:\code\python\pymediaconch> echo $LastExitCode
0
```

This should be a non-zero exit code to allow better error handling.

**Comment by JeromeMartinez** [comment]
Fixed in https://github.com/MediaArea/MediaConch_SourceCode/pull/717, should be OK in [latest snapshots](https://mediaarea.net/download/snapshots/binary/mediaconch-gui).
