### ISSUE TITLE
XSD Schema Unbounded Causes All elements to be treated as a 1...many cardinality

### ISSUE THREAD

**Issue by jsciame** [MediaArea/MediaInfo#591]
I was doing some work around pulling data out of mediainfo using the xsd and noticed an issue.
 
The xsd for trackType allows unbounded occurrence.

`<xsd:complexType name="trackType">
    <xsd:sequence>
        <xsd:choice maxOccurs="unbounded">`

And then each element specifies it only occurs once like the below
 
`<xsd:element name="FrameRate" minOccurs="0" maxOccurs="1" type="xsd:float"/>`

The xsd b/c of the maxOccurs = unbounded, it results in each element being a list and allows something like the below to validate. Was this your intention or is this a bug in the schema?  Currentyl, 2 FrameRate elements will return valid.

`<OverallBitRate_Mode>VBR</OverallBitRate_Mode>
            <OverallBitRate>188473606</OverallBitRate>
            <FrameRate>29.970</FrameRate>
            <FrameRate>29.970</FrameRate>
            <FrameCount>1110</FrameCount>
            <StreamSize>1048580</StreamSize>`

**Comment by JeromeMartinez** [comment]
@jsciame please confirm that https://github.com/MediaArea/MediaAreaXml/blob/24c9b2e25ae1fee90ed18e960222c9bfb2ad95fa/mediainfo.xsd is as you expect.

**Comment by jsciame** [comment]
@JeromeMartinez This looks better from our parsing library. All of the values are single values and the duplicate FrameRate field now fails validation.
