### ISSUE TITLE
HDR info missing for AV1 videos

### ISSUE THREAD

**Issue by cdgriffith** [MediaArea/MediaInfo#597]
All these fields are missing for AV1 HDR10 videos

```
HDR format                               : SMPTE ST 2086, HDR10 compatible
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0050 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 1000 cd/m2
Maximum Frame-Average Light Level        : 200 cd/m2
```

Attached is my own video, converted with SVT AV1.

https://user-images.githubusercontent.com/3275435/157154382-1a0a6a5d-4da5-4617-b254-6e0670c93c93.mp4

Can see the data in ffprobe: `ffprobe -i artist.mp4 -select_streams v:0 -show_frames -read_intervals %+#1`

```
[SIDE_DATA]
side_data_type=Mastering display metadata
red_x=17367/65536
red_y=45220/65536
green_x=9830/65536
green_y=3932/65536
blue_x=44564/65536
blue_y=20972/65536
white_point_x=20493/65536
white_point_y=21561/65536
min_luminance=82/16384
max_luminance=256000/256
[/SIDE_DATA]
[SIDE_DATA]
side_data_type=Content light level metadata
max_content=1000
max_average=200
[/SIDE_DATA]
```

**Comment by ValZapod** [comment]
It prints stuff now.

**Comment by cdgriffith** [comment]
I am on 22.06 on Windows and it does have the Mastering information now, but still no `HDR format` field

And instead of `Display P3` for Mastering color primaries it shows `Mastering display color primaries        : R: x=0.891280 y=0.419440, G: x=0.347340 y=0.904400, B: x=0.196600 y=0.078640, White point: x=0.409860 y=0.431220`

**Comment by JeromeMartinez** [comment]
> no HDR format field

`Mastering display color primaries` is present, so right, we should show a `HDR format` field.

> And instead of Display P3

There is a bug report by email about that, we mixed up the denominator (not the same in AV1 spec as in other specs), we have to fix that.

**Comment by alexdns1** [comment]
Any plans on fixing this @JeromeMartinez  ?

**Comment by JeromeMartinez** [comment]
Still planned but no ETA ([sponsored requests](https://mediaarea.net/Services) have priority), trying for next version.

**Comment by alexdns1** [comment]
@JeromeMartinez don't see a single mention of the word sponsor on that page :) If you are talking about support - sure how much do we have to pay to get this thing fixed ?

**Comment by JeromeMartinez** [comment]
> if you are talking about support - sure how much do we have to pay to get this thing fixed ?

Not much (it is very small, just currently in the long free support todo list). Please drop us an email at info@mediaarea.net

**Comment by JeromeMartinez** [comment]
Fun fact: the first AV1 file I received was using MPEG denominator (50000), and I based my quick dev on it (now this file is not more displayed as Display P3).
AV1 specs are explicit, it is a 65536 denominator in AV1, so bye bye this file... I guess it was a file created based on initial specs or with wrong read of specs.
