### ISSUE TITLE
MediaInfo XSD: FrameRate numerator and denominator should be int

### ISSUE THREAD

**Issue by plondino** [MediaArea/MediaInfo#604]
FrameRate_Num and FrameRate_Den are currently `xsd:float` in the schema but should be `xsd:integer`.  Is there ever a case where these would be float values?

```
<xsd:element name="FrameRate_Den" minOccurs="0" maxOccurs="1" type="xsd:float"/>
<xsd:element name="FrameRate_Num" minOccurs="0" maxOccurs="1" type="xsd:float"/>
```

**Comment by JeromeMartinez** [comment]
Source issue in MediaInfoLib data files, fixed in https://github.com/MediaArea/MediaInfoLib/pull/1529.
Then the generated XSD is fixed with https://github.com/MediaArea/MediaAreaXml/pull/51.

> Is there ever a case where these would be float values?

No.
