### ISSUE TITLE
XML OverallBitRate vs. OverallBitRate_String

### ISSUE THREAD

**Issue by ncamardo** [MediaArea/MediaInfo#617]
Hello,

In the newest update of MediaInfo (22.03) -- we are no longer seeing "OverallBitRate_String" with a measure in mbps or kbps in the XML. Now, we see "OverallBitRate" in the XML in bits. In a previous version (c. 2017, which was the last version we were using prior to this update) we were seeing "OverallBitRate_String" with a measure in mbps or kbps in the XML.

Can anyone speak to this update? Would it be possible to show the _string options in the XML?

**Comment by JeromeMartinez** [comment]
I don't remind that `_String` was by default in previous version, anyway: add ` --full` to the command line.

**Comment by ncamardo** [comment]
We're using the MediaInfo.dll in another program to pull the xml... is there a way to display _string instead of the other value? The known parameters indicates that there is a difference in units between these two parameters, but we're not sure how to prioritize one over the other.

**Comment by JeromeMartinez** [comment]
> We're using the MediaInfo.dll

`MediaInfo::Option("Complete", "1")` before `MediaInfo::Inform()`.

> we're not sure how to prioritize one over the other.

The precise value is the one in bytes (the element without `_String`) and is made for computing.
The others (with `_String`) are rounding of the first value and are made for direct display to users.
