### ISSUE TITLE
Why is the audio "Codec ID" numeric?

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaInfo#62]
I have the case where the audio format is "ADPCM" - and it writes "Codec ID: 2"
Or "AAC", which has "Codec ID: 40".

For video codecs, I've seen it's usually a somewhat human readable string. Like "XVID" or "avc1".

Where does the value for "Codec ID" come from?
Seems like referencing to some sort of lookup table...

Thanks for any hints! :)

**Comment by JeromeMartinez** [comment]
for e.g. AVI, video codec identifier is on 4 bytes ("FourCC") and audio codec identifier is on 2 bytes ("TwoCC"). In QuickTime, it is "FourCC" nearly everywhere (in some rares cases, a "mp4a" codec identifier is used, saying that the real codec identifier is somewhere else, in a MPEG descriptor, and in that case the audio "object type indicator" is on 1 byte).

> Where does the value for "Codec ID" come from?

Depends of the container format.
- AVI: FormatTag field in AVI / hdlr / strf / auds chunk for audio, Compression field in AVI / hdlr / strf / vids chunk for video...
- MP4 / QuickTime: the name of the "sub-atom" in the moov / trak / mdia / minf / stbl / stsd atom, with possiiblity of extension if the name is "mp4v" or "mp4a".
- MXF: concatenation of 8 last bytes of essence container label and 8 last bytes of essence compression label
- ...

> Seems like referencing to some sort of lookup table...

In MediaInfo, data in the CodecID field comes from the file, and the mapping between CodecID and the format comes from a lookup table (as any player).
[Here are my lookup tables](https://github.com/MediaArea/MediaInfoLib/tree/master/Source/Resource/Text/DataBase).

**Comment by pjotrek-b** [comment]
Thanks for clearing that up :)
