### ISSUE TITLE
MediaInfo Out TimeCode Not being calculated correctly for 23.98

### ISSUE THREAD

**Issue by jsciame** [MediaArea/MediaInfo#623]
We have a file that has timecode from 00:00:00:00 to 00:02:06:20 in 23.98 timecode. 

MediaInfo is showing the in out as 00:00:00:00 to 00:02:07:00

I did a calculation from 00:00:00:00 with a duration of 127002 milliseconds and I get 00:02:06:21.

MediaInfo Command line,
MediaInfoLib - v22.03

Other
Count                                    : 193
Count of stream of this kind             : 1
Kind of stream                           : Other
Kind of stream                           : Other
Stream identifier                        : 0
StreamOrder                              : 2
ID                                       : 3
ID                                       : 3
Type                                     : Time code
Format                                   : QuickTime TC
Format                                   : QuickTime TC
Commercial name                          : QuickTime TC
Duration                                 : 127002
Duration                                 : 2 min 7 s
Duration                                 : 2 min 7 s 2 ms
Duration                                 : 2 min 7 s
Duration                                 : 00:02:07.002
Duration                                 : 00:02:07:01
Duration                                 : 00:02:07.002 (00:02:07:01)
Frame rate                               : 23.976
Frame rate                               : 23.976 (24000/1001) FPS
FrameRate_Num                            : 24000
FrameRate_Den                            : 1001
Frame count                              : 3049
Time code of first frame                 : 00:00:00:00
Time code of last frame                  : 00:02:07:00
TimeCode_DropFrame                       : No
Time code, striped                       : Yes
Time code, striped                       : Yes
Language                                 : en
Language                                 : English
Language                                 : English
Language                                 : en
Language                                 : eng
Language                                 : en
Encoded date                             : UTC 2022-06-29 18:18:06
Tagged date                              : UTC 2022-06-29 18:18:06

**Comment by JeromeMartinez** [comment]
Closed by https://github.com/MediaArea/MediaInfoLib/pull/1565.
Due to relying on rounded frame rate in the time code header instead of the track frame rate.

**Comment by jsciame** [comment]
@JeromeMartinez  Confirming the snapshot from `20220709` is working as expected and returning the correct value for the test file for 23.98 timecode.

> Other
ID                                       : 3
Type                                     : Time code
Format                                   : QuickTime TC
Duration                                 : 2 min 7 s
Frame rate                               : 23.976 (24000/1001) FPS
Time code of first frame                 : 00:00:00:00
Time code of last frame                  : 00:02:06:20
Time code, striped                       : Yes
Language                                 : English
Encoded date                             : UTC 2022-06-29 18:18:06
Tagged date                              : UTC 2022-06-29 18:18:06
