### ISSUE TITLE
MediaInfo won't show Timecode Information in Datatrack of Sony Alpha XAVC mp4 File

### ISSUE THREAD

**Issue by se-wi** [MediaArea/MediaInfo#624]
it would be very useful if mediainfo could extract the timecode information of a Sony Alpha XAVC mp4 File. 
We know that this Video has TC because ffprobe (readout added) shows the Datatrack and Playersoftware (Telestream Switch) shows the TC as (sotc)
If needed i could provide a download-link to an original file

[C0003-mediainfo.txt](https://github.com/MediaArea/MediaInfo/files/9029007/C0003-mediainfo.txt)
[C0003-ffprobe.txt](https://github.com/MediaArea/MediaInfo/files/9029008/C0003-ffprobe.txt)

**Comment by pimswr** [comment]
Hi, we face the same problem here at SWR in Germany. Is there any chance to get it fixed ? Thx !

**Comment by JeromeMartinez** [comment]
@se-wi sorry I did not answer sooner.
@se-wi or @pimswr first we need a sample file.

**Comment by se-wi** [comment]
Hi Jerome, 
thanks for your response, i uploaded the example from the readouts here:
https://share.ard-zdf-box.de/s/FdWDmyBnnBq8EaQ

thx again 
se-wi

**Comment by JeromeMartinez** [comment]
We checked the provided file, we see like FFmpeg the rtmd track but if we understand well it is [real time metadata](https://exiftool.org/TagNames/Sony.html#rtmd) and not a time code.
Looking for some other places in the file with time code...

your FFmpeg output does not show the time code, right?
What is the display (time code value and more) of Playersoftware?

**Comment by JeromeMartinez** [comment]
By the way, free support is low priority, if you are interested in prioritizing such development [please let us know](https://mediaarea.net/Services).

**Comment by JeromeMartinez** [comment]
[dev snapshots](https://mediaarea.net/download/snapshots/binary/).
