### ISSUE TITLE
EBUCore XML: Typo "Writting"

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaInfo#63]
In MediaInfo's EBUCore XML output (v1.6), there is a typo in a technical attribute string:

> ebucore:technicalAttributeString typeLabel="Wri**tt**ingLibrary"
> ebucore:technicalAttributeString typeLabel="Wri**tt**ingApplication"

There should only be one "t".
e.g. "Wri**t**ingApplication"

**Comment by JeromeMartinez** [comment]
[Fixed](https://github.com/MediaArea/MediaInfoLib/commit/3da284a25e4eb03de6e2f3912cb8b47b329351e3), thanks.

**Comment by pjotrek-b** [comment]
Thanksalot :)
