### ISSUE TITLE
Video Format/Info present in text, not XML

### ISSUE THREAD

**Issue by ncam610** [MediaArea/MediaInfo#632]
I'm wondering if parameter Video, Format/Info is intentionally absent from XML. As an example, I'm looking at an MP4 file. Text view shows Video: Format/Info = Advanced Video Codec. The field is absent from the XML view of the same file. Is this intentional?

**Comment by JeromeMartinez** [comment]
`Format/Info` is for humans, XML is for machines.

This field is just a hint, and a [direct mapping](https://github.com/MediaArea/MediaInfoLib/tree/master/Source/Resource/Text/DataBase) from `Format`, so it can be rebuilt easily from the current XML without it.
