### ISSUE TITLE
Bit depth not displayed for video files?

### ISSUE THREAD

**Issue by lukeflegg** [MediaArea/MediaInfo#640]
Hello,
I'm looking through all the views and only seeing Bit Depth shown for the audio, not the video. Is this a bug or is there some way to display this? It's literally the 1 piece of information about the file I was trying to ascertain with MediaInfo.
https://i.imgur.com/WDDhRc7.png

**Comment by kieranjol** [comment]
I believe that mediainfo does not provide bit depth info for ProRes as there’s isn’t a clear indicator in the file that declares the bit depth. More info here https://sourceforge.net/p/mediainfo/discussion/297610/thread/4bc21b18/

**Comment by JeromeMartinez** [comment]
In addition to @kieranjol answer,

> only seeing Bit Depth shown for the audio

Depends also of the audio format, e.g. bit depth is not shown for MP3 or AAC, for a similar reason ("dynamic" bit depth, every frame should be entirely decoded for knowing the max bit depth of the content).
And bit depth is displayed for other video formats e.g. AVC, HEVC.
