### ISSUE TITLE
Access violation in module MediaInfo_i386.dll on opening specific mediafiles

### ISSUE THREAD

**Issue by RensvanderZwan** [MediaArea/MediaInfo#643]
On opening the sample media file in DLL (and GUI) in versions 22.03 and 22.06. 

Error popup in Gui:
Access violation at address 59709d10 in module MediaInfo_i386.dll. Read of address 00E4F000

I am Using mediainfo DLL in a C# .NET6 program. Access violations in DLL cannot be handled in user code since Microsoft has moved from .NET Framework to .NET Core.

Any idea how to deal with this?

Sample file: https://we.tl/t-4mUsQXlnds

**Comment by RensvanderZwan** [comment]
That would be great,

Thanks.

**Comment by JeromeMartinez** [comment]
[Fixed](https://github.com/MediaArea/MediaInfoLib/commit/3c1bf755c0e54df56072b92150153c0412657213).
