### ISSUE TITLE
mediaarea.net website down invalid certificate & PPA error

### ISSUE THREAD

**Issue by lucknaumann** [MediaArea/MediaInfo#659]
Hi. For the past two or so days the website has been down.

Checking https://downforeveryoneorjustme.com/mediaarea.net?proto=https results in:

> Is Mediaarea.net down?
> Checking if mediaarea.net is down or it is just you...
> It's not just you! [mediaarea.net](https://mediaarea.net/) is down.

I was alerted to this when attempting a repo update:

```bash
Fatal error: E: The repository 'https://mediaarea.net/repo/deb/ubuntu focal Release' no longer has a Release file.
W: Updating from such a repository can't be done securely, and is therefore disabled by default.
W: See apt-secure(8) manpage for repository creation and user configuration details.
E: https://mediaarea.net/repo/deb/ubuntu focal Release is not (yet) available (Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 45.56.78.187 443])
```

**Comment by JeromeMartinez** [comment]
Thank you for the report.
It seems that the certificate was not updated in one place, it is fixed.

**Comment by lucknaumann** [comment]
Thanks!
