### ISSUE TITLE
MediaInfoLib/Project/GNU/Library NOT EXIST

### ISSUE THREAD

**Issue by wishWinds** [MediaArea/MediaInfo#660]
from the README. 
```
cd MediaInfoLib/Project/GNU/Library
```
This is not exist

**Comment by JeromeMartinez** [comment]
> This is not exist

It is: https://github.com/MediaArea/MediaInfoLib/tree/master/Project/GNU/Library , and the directory should be there from the `git clone` command.
You may be interested in the "all in one" packages from [our source code download page](https://mediaarea.net/en/MediaInfo/Download/Source).

**Comment by wishWinds** [comment]
Thanks a lot.
