### ISSUE TITLE
Missing FPA Pass field from output

### ISSUE THREAD

**Issue by Maxranderson-itv** [MediaArea/MediaInfo#661]
Hello folks,

The FPA Pass field is missing from the JSON output. Unfortunately, I can't share the video with you guys but I'll put the outputs here. We can grep the value from the detailed output but would be nice to have it in the JSON output. Thanks in advance, you guys are doing a great job!

Output from `mediainfo -Details=1 {file}`
```
00030B7  Product Placement - No (5 bytes)
000030B7   Header (4 bytes)
000030B7    Code:                                32802 (0x8022)
000030B9    Length:                              1 (0x0001)
000030BB   Value:                                0 (0x00)
000030BC  FPA Pass - Yes (5 bytes)
000030BC   Header (4 bytes)
000030BC    Code:                                32803 (0x8023)
000030BE    Length:                              1 (0x0001)
000030C0   Value:                                0 (0x00)
000030C1  FPA Manufacturer - Manufacturer masked (46 bytes)
000030C1   Header (4 bytes)
000030C1    Code:                                32804 (0x8024)
000030C3    Length:                              42 (0x002A)
000030C5   Value:                                Manufacturer masked 
000030EF  FPA Version - 8.2.0 (14 bytes)
000030EF   Header (4 bytes)
000030EF    Code:                                32805 (0x8025)
000030F1    Length:                              10 (0x000A)
000030F3   Value:                                8.2.0
``` 

JSON Output
```
"ProductPlacement": "No",
"FpaManufacturer": "Manufacturer masked",
"FpaVersion": "8.2.0",
```

**Comment by JeromeMartinez** [comment]
> The FPA Pass field is missing

Oops, [ugly typo](https://github.com/MediaArea/MediaInfoLib/commit/bd3c3a36bffaebcd9b74026862e7198d73bb9b14) which makes the `FpaPass` value output only in some specific cases.

>  I can't share the video

We have a couple of UK DPP files, so no need, we saw the issue with the files we already have.
You can test [latest development snapshots](https://mediaarea.net/download/snapshots/binary/).

**Comment by Maxranderson-itv** [comment]
Oh my gosh! Thank you so much @JeromeMartinez ! Great job and have a good week!
