### ISSUE TITLE
Segfault when running on a TTML2 file

### ISSUE THREAD

**Issue by vevv** [MediaArea/MediaInfo#666]
When running MediaInfo v22.12 on a TTML2 file, I get a Segmentation fault. This doesn't happen on v22.09, v21.03 or any other version that I've previously used.

This happens on Ubuntu 18.04 LTS, with a custom build from [here](https://mediaarea.net/en/MediaInfo/Download/Source), as well as when using a binary extracted from [this .deb](https://mediaarea.net/download/binary/mediainfo/22.12/mediainfo_22.12-1_amd64.Debian_11.deb); as well as Ubuntu 22.04 with MediaInfo installed from the MediaArea repo. I was not able to reproduce this with the official Windows build.

Example file: [834a4288-280d-4159-b498-973a5ea75290.zip](https://github.com/MediaArea/MediaInfo/files/10300308/834a4288-280d-4159-b498-973a5ea75290.zip) (zipped for github)

**Comment by g-maxime** [comment]
Please test [library](https://mediaarea.net/download/snapshots/binary/libmediainfo0/20221228/), [sources](https://mediaarea.net/download/snapshots/binary/mediainfo/20221228/MediaInfo_CLI_22.12.20221228_GNU_FromSource.tar.xz)
