### ISSUE TITLE
Segfault when reading from STDIN

### ISSUE THREAD

**Issue by wofr06** [MediaArea/MediaInfo#670]
(under Ubuntu 22.04.1) mediainfo always crashes when reading jpg or png files and often when reading pdf files from STDIN, eg. `cat some.jpg|mediainfo -`. That happens both with the installed version 21.09 as well with the latest 22.10 (and newer libs).

**Comment by g-maxime** [comment]
Please test with [this library snapshot ](https://mediaarea.net/download/snapshots/binary/libmediainfo0/20230121-2/)

**Comment by wofr06** [comment]
I found still one sample png file where the segfault still occurs. File in question has been sent with private mail.

**Comment by JeromeMartinez** [comment]
> File in question has been sent with private mail.

We didn't receive it. Merging the PR as it fixes some of the issues, and waiting for a still crashing file.
