### ISSUE TITLE
StreamOrder missing in ST 436 tracks in MXF

### ISSUE THREAD

**Issue by plondino** [MediaArea/MediaInfo#673]
I have an XML output from an MXF and QuickTime version of the same media file with a EIA 708 CDP stream with cc1, cc3, service 1 and service 2.  The QuickTime version has the StreamOrder enumerated for the text streams (they are all in the same QuickTime c708 track) but it is missing on the text track in the MXF version.

QuickTime:
```
      <track type="Text" typeorder="4">      
      <Count>301</Count>      
      <StreamCount>4</StreamCount>      
      <StreamKind>Text</StreamKind>      
      <StreamKind_String>Text</StreamKind_String>      
      <StreamKindID>3</StreamKindID>      
      <StreamKindPos>4</StreamKindPos>      
      <StreamOrder>8</StreamOrder>
```
MXF:
```
    <track type="Text" typeorder="4">      
      <Count>301</Count>      
      <StreamCount>4</StreamCount>      
      <StreamKind>Text</StreamKind>      
      <StreamKind_String>Text</StreamKind_String>      
      <StreamKindID>3</StreamKindID>      
      <StreamKindPos>4</StreamKindPos>   
```

Is StreamOrder anything but a zero-based media file track order?  I.e. is it the same as ignoring e.g. timecode tracks and enumerating all the tracks in order in the file starting from zero?  I see a few other tickets e.g. #201  and #186 but I wasn't completely clear on the derivation of this value or if there's a specific reason the MXF doesn't have it.

[em06_prores_final_cut_pro.xml.txt](https://github.com/MediaArea/MediaInfo/files/10671172/em06_prores_final_cut_pro.xml.txt)
[em06_evs_2_7_4.mxf.xml.txt](https://github.com/MediaArea/MediaInfo/files/10671173/em06_evs_2_7_4.mxf.xml.txt)

**Comment by plondino** [comment]
It seems like the ID field uses the MXF Track ID in the source package - if the descriptor happened to be in a different order it would not match the track order?

Looking at the QuickTime example, since all the ancillary streams are in a QuickTime c708 track, they all have the same StreamOrder.  I would think all the ancillary streams in an MXF file would also have the same stream order number since they are in the same track.  I think it would be helpful to have this exposed for consistency between the formats.

**Comment by plondino** [comment]
Also curious on the definition of StreamKindID vs StreamKindPos.  For the MXF and QuickTime files I looked at, it seems that StreamKindID = typeorder - 1 and StreamKindPos = typeorder, but not sure if these values are getting pulled from somewhere.

```
    <track type="Text" typeorder="4">      
      <Count>301</Count>      
      <StreamCount>4</StreamCount>      
      <StreamKind>Text</StreamKind>      
      <StreamKind_String>Text</StreamKind_String>      
      <StreamKindID>3</StreamKindID>      
      <StreamKindPos>4</StreamKindPos>      
```

**Comment by JeromeMartinez** [comment]
> Also curious on the definition of StreamKindID vs StreamKindPos. For the MXF and QuickTime files I looked at, it seems that StreamKindID = typeorder - 1 and StreamKindPos = typeorder, but not sure if these values are getting pulled from somewhere.

It is that, it was requested to be not starting from 0 and it does not have so much sense actually, mistake from the past and now it stays forever. At some point I'll do a big clean up of field and remove actually non relevant fields.
