### ISSUE TITLE
Format field not updated in case of ER AAC ELD

### ISSUE THREAD

**Issue by 100820** [MediaArea/MediaInfo#675]
Hi,
I have observed some discrepancy with “Format” field reported in MediaInfo (version 22.12 on Windows) with ER ELD files.
The snippet on the right is for a conformance stream. Here, the “Format” is reported as “ER AAC ELD”. However, with another AAC ELD stream, “Format” is reported as “mp4a-40-39” (left snippet).  
![image](https://user-images.githubusercontent.com/97579762/220091219-828ce00b-34bd-4d08-b05c-f903d0f407b1.png)
https://user-images.githubusercontent.com/97579762/220089803-fa151cf6-2d03-4d9f-ae24-d988fbadc796.mp4

With some comparison with conformance stream I have found that hardcoding of ‘bs_start_freq’ and ‘bs_stop_freq’ fields in ‘esds’ box of mp4 header is needed to get the right “Format”, which I assume to be incorrect.
I have added an mp4 file before and after the mp4 header hard-coding for reference. Could you please let me know why these fields are expected to be hardcoded?
 https://user-images.githubusercontent.com/97579762/220089897-e86fd934-933f-4486-a63d-208d25d2eb62.mp4

**Comment by JeromeMartinez** [comment]
> I have added an mp4 file before and after the mp4 header hard-coding for reference.

Thank you for the files, we didn't have them so it was more or less theory for us, and we didn't implement everything (the "good" parsing was only luck).
[Done now](https://github.com/MediaArea/MediaInfoLib/pull/1671/files) (was actually very fast because we implemented the biggest missing part in the meanwhile, for another parsing).

**Comment by JeromeMartinez** [comment]
@100820 by curiosity what means `audioProfileLevelIndication` of 76? I have an old version of the spec and not willing to buy an up to date version but I could expand [this code](https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfo/Multiple/File_Mpeg4_Descriptors.cpp#L229-L319) if I have some clues.

Also: don't hesitate to send similar bug report with any format.

**Comment by 100820** [comment]
audioProfileLevelIndication of 76 pertain to Low Delay AAC v2 Profile @ L1

**Comment by JeromeMartinez** [comment]
@100820 thanks, I am adding it at https://github.com/MediaArea/MediaInfoLib/pull/1693.
If you have more hints about missing `audioProfileLevelIndication` there, don't hesitate to comment.
