### ISSUE TITLE
Publish to winget

### ISSUE THREAD

**Issue by LeoWinterDE** [MediaArea/MediaInfo#681]
WinGet is a package manager that allows Windows users to install apps via the command line; `winget install MediaInfo`.

There is no current version provided which makes installing MediaInfo a bit more involved than it need to be - https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/MediaArea/MediaInfo

Maybe include it in the release workflow?

**Comment by g-maxime** [comment]
Fixed by microsoft/winget-pkgs#98145
