### ISSUE TITLE
libmediainfo and mediainfo cli fails to read genre if genre is "Blues"

### ISSUE THREAD

**Issue by masterxq** [MediaArea/MediaInfo#682]
Hello *,

I found a crazy bug in mediainfo. If the genre is `Blues` mediainfo will read an empty genre. Same behavior in libmediainfo.

I have tested the following versions:
```
$ mediainfo --version
MediaInfo Command line, 
MediaInfoLib - v22.12
$ dpkg -l |grep libmediainfo
ii  libmediainfo-dev      22.12+dfsg-1    amd64    library reading metadata from media files -- headers
ii  libmediainfo0v5:amd64 22.12+dfsg-1    amd64    library for reading metadata from media files -- shared library
```

Tried 10 tracks. Tagged with easytag. Other software shows the genre correct.

**Comment by masterxq** [comment]
Appears caseinsensitiv. But changing a single letter or add a space fixes it.

**Comment by JeromeMartinez** [comment]
@masterxq please share a sample file.

**Comment by masterxq** [comment]
[file_example_MP3_1MG.zip](https://github.com/MediaArea/MediaInfo/files/10897502/file_example_MP3_1MG.zip)
```
$ mediainfo file_example_MP3_1MG.mp3 |grep -i genre
$
```
