### ISSUE TITLE
Mediainfo 22.12 hangs on Redhat

### ISSUE THREAD

**Issue by thorsted** [MediaArea/MediaInfo#693]
I have mediainfo installed on a Redhat 7 machine and it works majority of the time. Currently hangs on one particular MP4. Running the same MP4 on my Mac CLI, it outputs just fine. Not sure what the difference might be.

Here is the output from my Mac.

Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (isom/mp41/mp42)
File size                                : 219 MiB
Duration                                 : 12 min 34 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 2 439 kb/s
Movie name                               : project
Movie_More                               : This video is about project
Encoded date                             : UTC 2020-11-30 21:20:20
Tagged date                              : UTC 2020-11-30 21:31:31
thmb                                     : ÿØÿà

Video
ID                                       : 2
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings                          : CABAC / 2 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 2 frames
Format settings, GOP                     : M=1, N=30
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 12 min 34 s
Bit rate mode                            : Variable
Bit rate                                 : 2 309 kb/s
Maximum bit rate                         : 768 kb/s
Width                                    : 960 pixels
Height                                   : 540 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 29.970 (30000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.149
Stream size                              : 208 MiB (95%)
Title                                    : Core Media Video
Encoded date                             : UTC 2020-11-30 21:20:20
Tagged date                              : UTC 2020-11-30 21:31:31
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : avcC

Audio
ID                                       : 1
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 12 min 34 s
Source duration                          : 12 min 34 s
Bit rate mode                            : Constant
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 11.4 MiB (5%)
Source stream size                       : 11.4 MiB (5%)
Title                                    : Core Media Audio
Language                                 : English
Encoded date                             : UTC 2020-11-30 21:20:20
Tagged date                              : UTC 2020-11-30 21:31:31

**Comment by JeromeMartinez** [comment]
Please try a [development snapshot](https://mediaarea.net/download/snapshots/binary/libmediainfo0/), it may be already fixed.

**Comment by thorsted** [comment]
@JeromeMartinez, tested in v23.03 and file still hangs.

**Comment by JeromeMartinez** [comment]
We need the file, please share it (if not possible to have it public, send the link to my email address).

**Comment by thorsted** [comment]
> We need the file, please share it (if not possible to have it public, send the link to my email address).

Sent

**Comment by JeromeMartinez** [comment]
Sorry, didn't confirm we received it, just late on debug (not easy, it is fine on CentOS 8 etc, so we need to check specifically on CentOS 7).

**Comment by g-maxime** [comment]
What is the version number of mediainfo and libraries?
`rpm -qa libzen libmediainfo mediainfo`

**Comment by JeromeMartinez** [comment]
@thorsted please test one of the [development snapshots](https://mediaarea.net/download/snapshots/binary/libmediainfo0/).
