### ISSUE TITLE
CLI crashes on .wav file for EBUCore

### ISSUE THREAD

**Issue by ra-magnus-welander** [MediaArea/MediaInfo#695]
Steps to reproduce:
MediaInfo.exe lr_05132_01-mini.wav --output=EBUCore

I've tried this file in the GUI as well, it only shows a gray background with the message "(You must at least open one file)".

**Comment by ra-magnus-welander** [comment]
For some reason I can't upload the file, I will try to mail it instead.

**Comment by JeromeMartinez** [comment]
Crash confirmed with v22.12, seems already fixed (we fixed lot of crashes in the meanwhile) with v23.03 just released.

Note: it does not excuse a crash in MediaInfo but fix the date in the metadata :).

**Comment by ra-magnus-welander** [comment]
Great, thanks for the quick feedback and the fix! I've confirmed that 23.03 solves the problem.

Is it the "<ebucore:dateCreated startDate=" 07:44:04" />" that's the problem? I'm not the one generating these media files, so I need to know what to pass on to them.

**Comment by ra-magnus-welander** [comment]
Thank you very much for that detailed report!
