### ISSUE TITLE
Mediainfo 23.03: build fails (Problem while compiling MediaInfoLib)

### ISSUE THREAD

**Issue by Vouivre** [MediaArea/MediaInfo#696]
When I compile mediainfo 23.03 the build fails. You can get the log [here](http://pastebin.fr/123873).

I can compile mediainfo 22.12 without problem. 

My system

```
$ uname -a
Linux KISS 6.1.0 #6 SMP PREEMPT_DYNAMIC Mon Jan 16 07:26:08 UTC 2023 x86_64 GNU/Linux
```

I use the linux distribution kisslinux which is based on `musl`. I use the following tarball:

    https://mediaarea.net/download/binary/mediainfo/23.03/MediaInfo_CLI_23.03_GNU_FromSource.tar.xz

To compile mediainfo, I use

```
./CLI_Compile.sh 
 
cd MediaInfo/Project/GNU/CLI 
 
make DESTDIR="$1" install 
```

Tell me if you need more information.

**Comment by JeromeMartinez** [comment]
Fixed with https://github.com/MediaArea/MediaInfoLib/pull/1726, changes to do are at https://github.com/MediaArea/MediaInfoLib/commit/91d06a6fef303834cddc54f069f76f9113247a6a.

**Comment by Vouivre** [comment]
Great, thank you!
