### ISSUE TITLE
Incorrect detection of IMAX Enhanced for Independence Day (1996)

### ISSUE THREAD

**Issue by vstax** [MediaArea/MediaInfo#717]
According to the internets and my AVR, this movie has only DTS:X, not IMAX Enhanced. However mediainfo shows IMAX for some reason.
It is one of the movies where DTS:X wasn't detected until #422 was fixed. However, unlike "Charlie's Angels" in that ticket, this one is not supposed to have IMAX Enhanced.

I have 3 examples of actual IMAX Enhanced movies, here is output for them.
"Bad Boys for Life"
"Journey to the South Pacific"
"A Beautiful Planet"

Links to all the samples are sent by email.

**Comment by vstax** [comment]
Found an old (6+ yr) public DTS:X sample misdetected as IMAX: https://www.demolandia.net/downloads.html?id=53958226
(at least before the patch). Confirmed on my AVR that it doesn't have any IMAX Enhanced.

```
{
"creatingLibrary": {
"name": "MediaInfoLib",
"version": "23.03",
"url": "https://mediaarea.net/MediaInfo"
},
"media": {
"@ref": "dts-x-all-around-us-lossless-(www.demolandia.net).mkv",
"track": [
{
"@type": "General",
"UniqueID": "187100206417602782104877881437137910411",
"VideoCount": "1",
"AudioCount": "1",
"FileExtension": "mkv",
"Format": "Matroska",
"Format_Version": "4",
"FileSize": "167928561",
"Duration": "49.344",
"OverallBitRate_Mode": "VBR",
"OverallBitRate": "27225772",
"FrameRate": "23.976",
"FrameCount": "1183",
"IsStreamable": "Yes",
"Encoded_Date": "2016-02-06 18:18:52 UTC",
"File_Modified_Date": "2021-12-26 20:44:26 UTC",
"File_Modified_Date_Local": "2021-12-27 03:44:26",
"Encoded_Application": "mkvmerge v8.8.0 ('Wind at my back') 64bit",
"Encoded_Library": "libebml v1.3.3 + libmatroska v1.4.4"
},
{
"@type": "Video",
"StreamOrder": "0",
"ID": "1",
"UniqueID": "8954660026254812565",
"Format": "AVC",
"Format_Profile": "High",
"Format_Level": "4.1",
"Format_Settings_CABAC": "Yes",
"Format_Settings_RefFrames": "4",
"CodecID": "V_MPEG4/ISO/AVC",
"Duration": "49.341",
"Width": "1920",
"Height": "1080",
"Stored_Height": "1088",
"Sampled_Width": "1920",
"Sampled_Height": "1080",
"PixelAspectRatio": "1.000",
"DisplayAspectRatio": "1.778",
"FrameRate_Mode": "CFR",
"FrameRate": "23.976",
"FrameRate_Num": "24000",
"FrameRate_Den": "1001",
"FrameCount": "1183",
"ColorSpace": "YUV",
"ChromaSubsampling": "4:2:0",
"BitDepth": "8",
"ScanType": "Progressive",
"Delay": "0.000",
"Delay_Source": "Container",
"Encoded_Library": "x264 - core 148 r2597 e86f3a1",
"Encoded_Library_Name": "x264",
"Encoded_Library_Version": "core 148 r2597 e86f3a1",
"Encoded_Library_Settings": "cabac=1 / ref=4 / deblock=1:-1:-1 / analyse=0x3:0x113 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.15 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-3 / threads=12 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=crf / mbtree=1 / crf=15.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=20000 / vbv_bufsize=30000 / crf_max=0.0 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00",
"Language": "en",
"Default": "Yes",
"Forced": "No"
},
{
"@type": "Audio",
"StreamOrder": "1",
"ID": "2",
"UniqueID": "13289667000784747934",
"Format": "DTS",
"Format_Commercial_IfAny": "DTS-HD MA + IMAX Enhanced",
"Format_Settings_Mode": "16",
"Format_Settings_Endianness": "Big",
"Format_AdditionalFeatures": "XLL X IMAX",
"CodecID": "A_DTS",
"Duration": "49.344",
"BitRate_Mode": "VBR",
"Channels": "8",
"ChannelPositions": "Front: L C R, Side: L R, Back: L R, LFE, Objects",
"ChannelLayout": "C L R LFE Lb Rb Lss Rss Objects",
"SamplesPerFrame": "512",
"SamplingRate": "48000",
"SamplingCount": "2368512",
"FrameRate": "93.750",
"BitDepth": "24",
"Compression_Mode": "Lossless",
"Delay": "0.000",
"Delay_Source": "Container",
"Video_Delay": "0.000",
"Language": "en",
"Default": "Yes",
"Forced": "No"
}
]
}
}
```

**Comment by JeromeMartinez** [comment]
Now I doubt I can find a template for catching IMAX vs not IMAX.
I let it as is until something better for sure than what FFmpeg does.
For gathering all we have, the first 16 bytes are listed here + expected result + short name of title, I'll fill more when I have more.

```
02 00 08 50 28 4B 38 86 B1 00 7D 00 5B 82 6E 21 | Not MA | Not IMAX | Furious6
02 00 08 50 28 4B 38 86 B1 00 7D 00 5B 82 6E 21 | Not MA | Not IMAX | Furious7
02 00 08 50 28 4B FA 71 0D 62 02 FA 02 DC 13 71 |     MA | ?        | DTSX Emulator
02 00 08 50 28 4B FA 71 0D 62 02 FA 02 DC 13 71 |     MA | ?        | DTS X out of the box
F1 40 00 D0 30 28 4B 00 E1 00 02 0C F7 F7 89 A8 |     MA | IMAX     | Badboys
F1 40 00 D0 30 28 4B 00 E1 00 02 0C F7 F7 89 A8 |     MA | IMAX     | Journey
F1 40 00 D0 30 28 4B 00 E1 00 02 0C F7 F7 89 A8 |     MA | IMAX     | Planet
F1 40 00 D0 30 28 4B 04 B0 20 00 01 28 06 83 3D |     MA | Not IMAX | DTS X all around us demo
F1 40 00 D1 30 28 4B 00 E0 00 39 00 01 41 9E FE |     MA | Not IMAX | Independence
F1 40 00 D1 30 28 4B 00 E0 00 39 00 01 41 9E FE |     MA | ?        | Whiskey
```

**Comment by JeromeMartinez** [comment]
So I am going to merge https://github.com/MediaArea/MediaInfoLib/pull/1752, the only "false positive" would be DTS X all around us demo, better than current behavior.

**Comment by JeromeMartinez** [comment]
> Manual for DTS/DTS-HD, 2018 edition:

I used this one, but there is nothing in it about DTS:X (IMAX or not). `XXCh` theoretically accepts up to 32 additional channels but it is not used.

>  https://www.etsi.org/deliver/etsi_ts/103400_103499/103491/01.01.01_60/ts_103491v010101p.pdf

It seems a completely different format.

**Comment by vstax** [comment]
> It seems a completely different format.

Yes I guess you are right. Sorry to mislead you. While it does mention DTS:X (e.g. on page 63), apparently DTS:X is the marketing name for everything: object-based formats found in movie theaters, consumer media (what we are discussing), and streaming/broadcasting, which all are different formats. This document is about streaming/broadcasting DTS:X (technical name DTS-UHD), not the consumer media DTS:X.

They are definitely related (e.g. https://developer.android.com/reference/kotlin/android/media/AudioFormat and https://www.iana.org/assignments/media-types/audio/vnd.dts.uhd show that) but yes DTS-UHD is not DTS-HD so it doesn't help here.

> So I am going to merge https://github.com/MediaArea/MediaInfoLib/pull/1752, the only "false positive" would be DTS X all around us demo, better than current behavior.

Makes sense, until some other obvious example or proper documentation is found.

**Comment by JeromeMartinez** [comment]
Dev snapshot: [Windows](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20230423-4/MediaInfo_GUI_23.03.20230423_Windows.exe), [macOS](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20230423-4/MediaInfo_GUI_23.03.20230423_Mac.dmg).
