### ISSUE TITLE
libmediainfo in TinyMediaManager

### ISSUE THREAD

**Issue by funose** [MediaArea/MediaInfo#719]
Hello everyone and thank you for your work.

I use TinyMediaManager and since uploading Fedora version 38 it crashes.
The TinyMediaManager team tells me that libmediainfo is responsible for the crash.
Is it possible to get help?

Here discussion : https://gitlab.com/tinyMediaManager/tinyMediaManager/-/issues/2163

**Comment by JeromeMartinez** [comment]
the URL is not accessible (deleted?).
there were a couple of issues with 21.03 version, we have 21.04 version released, please update libmediainfo with [our builds](https://mediaarea.net/en/MediaInfo/Download/Fedora).

**Comment by funose** [comment]
Great. it works with version 23.04

THANKS.
