### ISSUE TITLE
Save export with same filename and location as original.

### ISSUE THREAD

**Issue by Snake883** [MediaArea/MediaInfo#741]
Save the export file name with the same name as the file.
Save the export in the same folder location as the original file.
Only the extension would be different (.txt, .nfo, etc).

**Comment by JeromeMartinez** [comment]
We do that with e.g. [BWF MetaEdit](https://mediaarea.net/BWFMetaEdit), it makes sense to do that with MediaInfo too.
When we have a bit of free time...

**Comment by cjee21** [comment]
Made a PR for this. It'll reduce the amount of clicks and typing required for my use case of export.
