### ISSUE TITLE
[Linux] Media files open MediaInfo instead of the media player.

### ISSUE THREAD

**Issue by TheArgentinian** [MediaArea/MediaInfo#748]
After installing Mediainfo, it becomes the default app for media files (audio and video). 
It has happened with multiple distros. 
Very annoying behavior.

**Comment by optio50** [comment]
This has nothing to do with Mediainfo.
Right click on a media file in a file explorer select properties and choose the default program to open with.

**Comment by TheArgentinian** [comment]
> This has nothing to do with Mediainfo. Right click on a media file in a file explorer select properties and choose the default program to open with.

This has everything to do with MI. Do you think the OS chooses what app open what file type?

**Comment by g-maxime** [comment]
> > This has nothing to do with Mediainfo. Right click on a media file in a file explorer select properties and choose the default program to open with.
> 
> This has everything to do with MI. Do you think the OS chooses what app open what file type?

The  MediaInfo.desktop file lists the filetypes MediaInfo can open. This makes it easily accessible in the 'open with' dialog.

There's no priority mechanism inside the .desktop file. When multiple applications can open the same file, the OS is responsible for which one it presents as the default. And the user can change this parameter through their file manager or the `xdg-mime` command.
