### ISSUE TITLE
MediaInfo 23.07 is still not DPI awareness

### ISSUE THREAD

**Issue by NewUserHa** [MediaArea/MediaInfo#750]
MediaInfo 23.07 is still not DPI awareness, this issue is since from version 18.05.
![image](https://github.com/MediaArea/MediaInfo/assets/32261870/3b0e9597-55d0-4165-900b-63012cc09033)
very blurry
vs
manually changed dpi by application:
![image](https://github.com/MediaArea/MediaInfo/assets/32261870/e49a3293-2620-48dc-bda0-a112f658f079)

win10

**Comment by JeromeMartinez** [comment]
> maybe the developer still use 1080p monitor

True. also our sponsors, so not their priority, but we understand that this is annoying, we need at some point to find how to fix that.
Patch welcome if you know.

**Comment by cjee21** [comment]
If manually setting the DPI works as mentioned in the first post, adding the following to the manifest should do it. No other changes needed if everything is displayed properly after enabling high DPI.

```xml
<asmv3:application>
    <asmv3:windowsSettings>
        <dpiAware>true</dpiAware>
        <dpiAwareness>PerMonitorV2</dpiAwareness>
    </asmv3:windowsSettings>
</asmv3:application>
```

**Comment by cjee21** [comment]
I tried implementing high DPI support to MediaInfo. Here's how it looks compared to existing version at 150% scale.
<img width="1157" alt="Screenshot 2024-05-18 212844" src="https://github.com/MediaArea/MediaInfo/assets/77721854/bb4744ad-d0e3-464d-b547-bc895482b322">

Overall everything seems to look fine. There's a bit of alignment difference in the menu bar and the sponsor(AD) button became blue on hover for some reason. I do not know how to further improve this.

**Comment by cjee21** [comment]
I fixed the sponsor(AD) button became blue on hover issue. Does this look okay? (screenshots taken with DPI set to 150% scale)
<img width="606" alt="Screenshot 2024-05-19 001821" src="https://github.com/MediaArea/MediaInfo/assets/77721854/6baed69e-1444-4d53-8910-beac641a67ec">
<img width="606" alt="Screenshot 2024-05-19 001848" src="https://github.com/MediaArea/MediaInfo/assets/77721854/54557753-6505-4999-8c79-b90f1012e042">
<img width="606" alt="Screenshot 2024-05-19 001859" src="https://github.com/MediaArea/MediaInfo/assets/77721854/f136cbb3-0ef4-4838-b6d4-7e2429f1ea89">

Should I create a pull request?

**Comment by JeromeMartinez** [comment]
> Should I create a pull request?

It would be greatly appreciated!

> I noticed the official MediaInfo is not built with DEP and ASLR enabled?

We checked a bit that some time ago but didn't finish to check as we don't know much about it so we weren't sure about what we do, if you have a patch ready we take it :).

**Comment by cjee21** [comment]
> We checked a bit that some time ago but didn't finish to check as we don't know much about it so we weren't sure about what we do, if you have a patch ready we take it :).

For enabling DEP and ASLR, just need to enable these two options in Project Options:
![Screenshot 2024-05-19 153510](https://github.com/MediaArea/MediaInfo/assets/77721854/9a241a3f-aef0-4434-a138-a3e29a89a96f)

It appears to be auto-enabled here so I don't know whether these settings are saved in the project file or not.
