### ISSUE TITLE
Display Aspect Ratio issues with XML and JSON output

### ISSUE THREAD

**Issue by aczzi** [MediaArea/MediaInfo#761]
Hello,

I have an issue on Display Aspect Ratio with option XML and JSON.

mediainfo SD_1_85.mov                                  returns :  Display aspect ratio                     : 1.85:1
mediainfo SD_1_85.mov --output=OLDXML returns :  <Display_aspect_ratio>1.85:1</Display_aspect_ratio>
mediainfo SD_1_85.mov --output=XML         returns:  <DisplayAspectRatio>1.821</DisplayAspectRatio>
mediainfo SD_1_85.mov --output=JSON       returns :  "DisplayAspectRatio": "1.821",

1.85:1 should be 1.85

mediainfo SD_4_3.mov                                    returns : Display aspect ratio                     : 4:3
mediainfo SD_4_3.mov --output=OLDXML   returns : <Display_aspect_ratio>4:3</Display_aspect_ratio>
mediainfo SD_4_3.mov --output=XML          returns : <DisplayAspectRatio>1.366</DisplayAspectRatio>
mediainfo SD_4_3.mov --output=JSON        returns : "DisplayAspectRatio":"1.366",

4:3 should be 1.33

How can we fix it ?
Many Thanks

**Comment by JeromeMartinez** [comment]
`OLDXML` is very old and no more maintained (at least in free support).
Default output is as expected (a string display, not a number)
`XML` and `JSON` have the expected value (numbers, and not rounded to a know aspect ratio)

What exactly (which output "format") is expected to be fixed?

**Comment by aczzi** [comment]
Thanks Jerome,

I think, I have a walkaround with option -f
        "DisplayAspectRatio": "1.366",
        "DisplayAspectRatio_String": "4:3",
 We would expect to have at least 2 decimals matching the division in numbers format : 4/3  = 1.33 or 1.85/1 = 1.85 
 But as you mentioned (numbers, and not rounded to a known aspect ratio).
 Thanks for your quick answer.
