### ISSUE TITLE
how to compile an arm64 version?

### ISSUE THREAD

**Issue by n0thing2speak** [MediaArea/MediaInfo#765]
I can't find any libmediainfo* libzen* aarch64 version, so how to compile an debian 11 arm64 MediaInfo?

**Comment by g-maxime** [comment]
Currently, we only have ARM binaries for Raspbian.

The build procedure indicated in the README.md should also work for arm64 Debian. Alternatively, you can build from the bundled sources packages ([CLI](https://mediaarea.net/download/binary/mediainfo/23.10/MediaInfo_CLI_23.10_GNU_FromSource.tar.xz), [GUI](https://mediaarea.net/download/binary/mediainfo-gui/23.10/MediaInfo_GUI_23.10_GNU_FromSource.tar.xz))

**Comment by n0thing2speak** [comment]
> Currently, we only have ARM binaries for Raspbian.
> 
> The build procedure indicated in the README.md should also work for arm64 Debian. Alternatively, you can build from the bundled sources packages ([CLI](https://mediaarea.net/download/binary/mediainfo/23.10/MediaInfo_CLI_23.10_GNU_FromSource.tar.xz), [GUI](https://mediaarea.net/download/binary/mediainfo-gui/23.10/MediaInfo_GUI_23.10_GNU_FromSource.tar.xz))

Ah sorry, I understand now. There is no need to follow the readme compilation tutorial, as you will run into various dependency issues. Just run CLI_Compile.sh directly. Thank you
