### ISSUE TITLE
Release 23.11 was tagged before version bumps were made in the source

### ISSUE THREAD

**Issue by bassmadrigal** [MediaArea/MediaInfo#784]
Release 23.11 was tagged before aa473b3, so version numbers in the program still show as 23.10.

**Comment by JeromeMartinez** [comment]
Which platform? Tested on Windows and Linux
![image](https://github.com/MediaArea/MediaInfo/assets/1641638/8efb9cdd-01db-44cb-beeb-878345bccff5)


```
$ mediainfo --version
MediaInfo Command line,
MediaInfoLib - v23.11
$ apt info mediainfo
Package: mediainfo
Version: 23.11-1
```

**Comment by g-maxime** [comment]
Fixed now
