### ISSUE TITLE
List fonts (attachments) from the c library

### ISSUE THREAD

**Issue by zoriya** [MediaArea/MediaInfo#790]
Hello,

I am trying to retrieve the list of attachments from the c API but can't find how to. At first, I trought it would be the same kind of api as for chapters so something like the pseudo go code bellow:
```go
chapters_begin := mi.Parameter(mediainfo.StreamMenu, 0, "Chapters_Pos_Begin")
chapters_end := mi.Parameter(mediainfo.StreamMenu, 0, "Chapters_Pos_End")

for i := chapters_begin; i < chapters_end; i++ {
	start := mi.GetI(mediainfo.StreamMenu, 0, i, mediainfo.InfoName)
	name := mi.GetI(mediainfo.StreamMenu, 0, i, mediainfo.InfoText)
}
```

but I could not find any property with a name close to attachments or extra (greping the source code of MeidaInfo did not really help).

**Comment by JeromeMartinez** [comment]
There is no specific MI stream for attachments, we just list the attachment names in one single MI field.
with MediaInfo CLI `mediainfo --Language=raw` or API `mi.Option("Language", "raw"); mi.Inform()` you have the key to use with `mi.Get()`.

**Comment by zoriya** [comment]
I'm sorry, I did not realize that every field in the cli was the name of the `mi.Parameter()`. I could not find a field "Attachments" in the ```mi.Option("info_parameters", "")``` call and assumed it did not exist.

Thanks for the help and the great library!
