### ISSUE TITLE
24.01 two error messages appear again

### ISSUE THREAD

**Issue by Klaus1189** [MediaArea/MediaInfo#796]
24.01 has same issue as previous 23.11: 
https://github.com/MediaArea/MediaInfo/issues/782
23.11.1 fixed it

![24 01_1](https://github.com/MediaArea/MediaInfo/assets/10894455/1fd86310-b6b1-4761-aa68-218fcdb70354)
![24 01_2](https://github.com/MediaArea/MediaInfo/assets/10894455/a3321fc0-1bce-4034-98b2-9a11697b6773)

**Comment by JeromeMartinez** [comment]
We forgot to merge https://github.com/MediaArea/MediaInfo/pull/783 😨🤦‍♀.

**Comment by JeromeMartinez** [comment]
v24.01.1 released.
