### ISSUE TITLE
Recognition of BW64 headed wav

### ISSUE THREAD

**Issue by WernerBleisteiner** [MediaArea/MediaInfo#822]
As mentioned elsewhere, MediaInfo does not recognise BW64 headed wav files at all (double-checked with most recent 24.03).
BW64, as defined in [ITU-R. BS2088](https://www.itu.int/dms_pubrec/itu-r/rec/bs/R-REC-BS.2088-1-201910-I!!PDF-E.pdf), is the successor of RF64. [EBU TECH 3306-2](https://tech.ebu.ch/docs/tech/tech3306.pdf) has no specs included, just points towards BS.2088.
However, RF64 still being used when authoring Dolby Atmos ADM (and non-ADM multichannel audio).
BW64 is now being consequently applied for files >4GB in the most recent [EPS 1.1](https://github.com/ebu/ear-production-suite).
Trying to access any BW64 information with MediaInfo delivers no results at all (apart from file size).
Tricking it by manipulating the first 4 bytes to "RF64", however, retrieves all info. See attached screenshot.
![image](https://github.com/MediaArea/MediaInfo/assets/22868982/c7f29f33-4692-44ce-a76f-9cad3bc4ce8c)
The main (only?) difference between BW64 and RF64 seems to be the sequence of ADM related chunks <chna> and <axml>: in RF64 they're attached after <data>, in BW64 they're at the very beginning of the file (as shown also in the screenshot).

**Comment by JeromeMartinez** [comment]
> The main (only?) difference between BW64 and RF64 seems to be the sequence of ADM related chunks and : in RF64 they're attached after , in BW64 they're at the very beginning of the file

The structure of a WAV file is specifically made for not being dependent of the sequence order...

> Tricking it by manipulating the first 4 bytes to "RF64", however, retrieves all info.

So someone decided that it would be funny to make RF64 aware tools blind with a RF64 with bext by changing only 2 bytes instead of letting them play the file as a BWF file can be played by a non bext aware tool, hum...

any, "BW64" thing support added, in next version.

**Comment by WernerBleisteiner** [comment]
> So someone decided that it would be funny to make RF64 aware tools blind with a RF64 with bext by changing only 2 bytes instead of letting them play the file as a BWF file can be played by a non bext aware tool, hum...
> 
Maybe it was a 'Joker' - or whoever were involved in writing the specs....
One assumption: probably loading of ADM data was meant to be loaded quicker and before the bulk of audio data?
Kudos!🙏🏻
