### ISSUE TITLE
The theme always follows Windows

### ISSUE THREAD

**Issue by Lt-knb** [MediaArea/MediaInfo#870]
It should be possible to force light mode and dark mode in Preferences.
Following Windows should be optional.

I'll keep using the previous version until this is implemented

**Comment by JeromeMartinez** [comment]
It was implemented it without saving it in preferences as it was easier for the person who implemented it (not from the core team) and we didn't yet add the option in the preferences to be saved.
We'll add it this summer when it is quieter with the sponsor requests.

**Comment by JeromeMartinez** [comment]
[implemented](https://github.com/MediaArea/MediaInfo/pull/871) by @cjee21, thank you much.
[dev snapshot](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20240618-2/MediaInfo_GUI_24.05.20240618_Windows.exe).

**Comment by JeromeMartinez** [comment]
In v24.06.
