### ISSUE TITLE
24.06 - some pixels or cut off text and "moved" object in options dialog

### ISSUE THREAD

**Issue by Klaus1189** [MediaArea/MediaInfo#889]
I just updated my MediaInfo installation (portable) to 24.06 and encountered some issues. But I don't know if these were already present in previous versions. I could check if you want me to.

Steps to reproduce
unpack the portable archive and first start, the nyou will see the issue I captured with the screenshot:
https://drive.google.com/file/d/1iR0_bAIL8KPLDwADK94USt4ubb6b8Q7H/view?usp=sharing

Please let me know if you need me to do anything else for you

**Comment by cjee21** [comment]
24.05
![Screenshot 2024-06-29 105502](https://github.com/MediaArea/MediaInfo/assets/77721854/98dc6eca-d4d3-4df3-9798-de7c88ecf637)

24.06
![Screenshot 2024-06-29 105543](https://github.com/MediaArea/MediaInfo/assets/77721854/3cd5373e-7cd2-40f2-a219-a92755d8322e)

The only change is added new setting as far as I know. The top "cut off text" is a high-DPI glitch that sometimes appear. Previously, something similar was noticed on the main window as well during testing.

**Comment by cjee21** [comment]
@JeromeMartinez I suspect the glitch is due to these page tabs/selectors not hidden enough so the currently active one is slightly visible on very high DPI scaling sometimes.

![Screenshot 2024-06-29 131429](https://github.com/MediaArea/MediaInfo/assets/77721854/446fa98a-22b1-4aaf-98ff-23ad51d11f02)

**Comment by JeromeMartinez** [comment]
Still open due to
![image](https://github.com/MediaArea/MediaInfo/assets/1641638/0d66bde4-1d72-4736-989c-41d9335d7d98)

@Klaus1189 correct me if I miss something.

**Comment by Klaus1189** [comment]
> Still open due to ![image](https://private-user-images.githubusercontent.com/1641638/344415596-0d66bde4-1d72-4736-989c-41d9335d7d98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2Nzk3OTksIm5iZiI6MTcxOTY3OTQ5OSwicGF0aCI6Ii8xNjQxNjM4LzM0NDQxNTU5Ni0wZDY2YmRlNC0xZDcyLTQ3MzYtOTg5Yy00MWQ5MzM1ZDdkOTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjlUMTY0NDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTJhYjUxYjg4NjE0MzNlODI5OThhOGQzYTM0ZmJmYmMwYzc2NzU0ZDAxYTE0NzE3NDM5ZDIyNWEzYTRhNzkxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G9scyhJit2MF2lNKhx9oJMgmJBncuskd0XECDsG_158)
> 
> @Klaus1189 correct me if I miss something.

same for me in 200% and I set my monitor for testing to 100% and I can confirm @JeromeMartinez

**Comment by cjee21** [comment]
Good news, I came across the solution to this while checking the other issue. Turns out the issue is at the tree view and not the sheet.

Is this good enough now?
| 100% | 200% |
| - | - |
| ![Screenshot 2024-06-30 133803](https://github.com/MediaArea/MediaInfo/assets/77721854/c2decc8b-3fd8-432e-8d58-92550eb4c107) | ![Screenshot 2024-06-30 133537](https://github.com/MediaArea/MediaInfo/assets/77721854/f6e26f29-f008-454e-94fb-c2745b63b5d7) |

**Comment by Klaus1189** [comment]
I like the dark ones, somehow the light versions look different from the dark ones, I mean a bit off.
And the light 200% has a OK button which is cut off the rounded window. Strange Win11
The more I look I think the dark screenshots have another radius of the rounded corners.
Best is a small testbuild if you don't mind.

**Comment by cjee21** [comment]
> Best is a small testbuild if you don't mind.

Testbuild need @JeromeMartinez I cannot upload my unsigned self-built version here without permission.

**Comment by cjee21** [comment]
> And the light 200% has a OK button which is cut off the rounded window.

Many buttons placed too close to the edges in my opinion. I added more margins to all elements in the about window but didn't change this.

**Comment by JeromeMartinez** [comment]
@cjee21 in your screenshots the dark them has alignment but the light theme has 1 bit diff, weird.

> I added more margins to all elements in the about window but didn't change this.

I could be fine with that, I created that 20 years ago and didn't care so much about such details but if someones improves it I take it :).

**Comment by cjee21** [comment]
> I could be fine with that, I created that 20 years ago and didn't care so much about such details but if someones improves it I take it :).

Done.

**Comment by JeromeMartinez** [comment]
[dev snapshot](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20240630-2/MediaInfo_GUI_24.06.20240630_Windows.exe) (before the margins).

**Comment by Klaus1189** [comment]
> [dev snapshot](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20240630-2/MediaInfo_GUI_24.06.20240630_Windows.exe) (before the margins).

looks good to me, not perfect, but I would leave it like that. Just one last cosmetic change:
Place the labels and the drop down lists on one height:
https://drive.google.com/file/d/1yxzdHjFnnvwQVh-XnYjlKO2U00LwhXJZ/view?usp=sharing

**Comment by JeromeMartinez** [comment]
[updated dev snapshot](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20240630-4/MediaInfo_GUI_24.06.20240630_Windows.exe).

**Comment by cjee21** [comment]
> Perhaps the two More buttons same height position and height size like the left of it. 

This is some DPI scaling issue. It is exact same height/position on 100%. Same as the button next to filename selector on main window.

**Comment by JeromeMartinez** [comment]
Good enough for the moment, I merge and if someone is motivated for checking this 200% DPI issue I would be happy to get the patch else it will stay as is.

**Comment by Klaus1189** [comment]
Looks good to me.

**Comment by Klaus1189** [comment]
> [updated dev snapshot](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20240630-4/MediaInfo_GUI_24.06.20240630_Windows.exe).
Looks good to me on 200%
