### ISSUE TITLE
Character police issue

### ISSUE THREAD

**Issue by JeromeMartinez** [MediaArea/MediaInfo#893]
(Received by email)

I have used Mediainfo for a number of years and I find it very useful.
I just updated to Mediainfo for Windows 24.06 but I find the text output is much lighter and thinner, I prefer the bolder text of the previous version I had which was 24.01.1
I reinstall the previous version and the bold and darker text returned, is this a deliberate lightening of the text output? How do I get the bolder and darker text display with your new version? if I cannot I will just stick to 24.06 and disable the check for update function.

cc @cjee21 for comment.

**Comment by cjee21** [comment]
Possibilities:
1. Use bold version of Cascadia Mono.
2. Add font selection so users can choose any font they like (harder to implement).

Whatever font is chosen, I guess cannot satisfy everyone. So number 2 is the only way to satisfy everyone.

**Comment by JeromeMartinez** [comment]
> So number 2 is the only way to satisfy everyone.

I am fine with your update so I guess that it is the only way (reason MI command line has so many options...).
As well as font size, criticized in the past.

No pressure as it is on your free time but if you are interested in coding that (font name, bold, size), we are interested ;-).

**Comment by cjee21** [comment]
> No pressure as it is on your free time but if you are interested in coding that (font name, bold, size), we are interested ;-).

Right now my priority is on 64-bits and Windows 11 context menu to be honest. Those are what actually matters for my use. The other parts are almost perfect already for me.

By the way, I have been using MediaInfo for years (can't remember when started). Thank you for this one-and-only app that enables me to view insights of media files, learn more about various codecs and check that my files have the correct streams, codecs,  metadata etc. Glad that I can contribute to it.

**Comment by cjee21** [comment]
Bold font test:
![Screenshot 2024-06-30 114925](https://github.com/MediaArea/MediaInfo/assets/77721854/b56a1be5-0a69-40b2-b700-a4264ff8843f)

@JeromeMartinez let you decide whether to use bold or no bold. Cascadia Mono actually has many font weights but VCL seems to only be bold or no bold with no in-between.

**Comment by cjee21** [comment]
If increase font size instead:
![Screenshot 2024-06-30 123735](https://github.com/MediaArea/MediaInfo/assets/77721854/52780a5d-f4c3-4818-a993-90043f6ca306)

**Comment by JeromeMartinez** [comment]
Increase of police size as an impact of having less content displayed, doesn't seem to be the case with bold.
I am checking before/after the change, looks like that bold could be a good intermediate, changing the font for a more clear one but using bold for something more similar to the past, for the default (and only one until we implement font choice).

@cjee21 are you fine with bold?

**Comment by cjee21** [comment]
> @cjee21 are you fine with bold?

Still better than the old jagged edges font I guess.

**Comment by JeromeMartinez** [comment]
> Still better than the old jagged edges font I guess.

Would you mind to do a PR?

**Comment by cjee21** [comment]
@JeromeMartinez I managed to use the semi bold variant of Cascadia Mono (required the exact correct name)

![Screenshot 2024-07-01 160732](https://github.com/MediaArea/MediaInfo/assets/77721854/824f6610-e7fb-455e-bda1-3daf6d505a65)

I think this one looks the best for MediaInfo compared to regular and bold. What do you think? Another PR?

**Comment by JeromeMartinez** [comment]
> I think this one looks the best for MediaInfo compared to regular and bold. What do you think? Another PR?

Yes, please.
By the way, the bold and semi-bold seem to show a bigger issue about the lack of space between the characters and the left toolbar, could you add some margin there while you are on that?

**Comment by cjee21** [comment]
> could you add some margin there while you are on that?

Sure, just need to enable auto margins. How about the background colour? That is changeable too.

**Comment by JeromeMartinez** [comment]
> How about the background colour? That is changeable too.

I have no strong preference there, little preference for not changing all.

**Comment by cjee21** [comment]
Just testing. This is how it looks on white.

![Screenshot 2024-07-01 162222](https://github.com/MediaArea/MediaInfo/assets/77721854/5e2d129f-48f8-4191-9e2a-bdbc835668e8)

**Comment by JeromeMartinez** [comment]
> Just testing. This is how it looks on white.

Let's try that.

**Comment by cjee21** [comment]
By the way, are the text in all the views supposed to be editable? Just discovered that they are editable.

**Comment by JeromeMartinez** [comment]
> By the way, are the text in all the views supposed to be editable? 

Not really :).
but important that they can be copied/pasted, IIRC (it was a very long time ago) I changed that for being copied/pasted.

**Comment by cjee21** [comment]
> > By the way, are the text in all the views supposed to be editable?
> 
> Not really :). but important that they can be copied/pasted, IIRC (it was a very long time ago) I changed that for being copied/pasted.

Read-only mode is still copy-able :)
