### ISSUE TITLE
Export icon is missing

### ISSUE THREAD

**Issue by Emiritus1** [MediaArea/MediaInfo#894]
The export icon is missing. Version 24.06

![Mediainfo](https://github.com/MediaArea/MediaInfo/assets/148827424/5644864c-981e-40e5-9fec-622d191e1a94)

**Comment by cjee21** [comment]
No bug. Because no file is open. Isn't it been always like that? @JeromeMartinez

**Comment by JeromeMartinez** [comment]
@cjee21 it seems that in light theme there are some glitches, the export button is not there if no file but it is greyed out in dark mode. Would you mind to make the theme coherent? I am fine with both (or maybe... Now actually prefer the greyed out one) but I would like coherency in the theme.

**Comment by cjee21** [comment]
> Would you mind to make the theme coherent? 

Looks like have to manually add disabled images. I'll add them. No idea why dark theme automatically had it.

**Comment by JeromeMartinez** [comment]
[dev snapshot](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20240630-3/MediaInfo_GUI_24.06.20240630_Windows.exe)
