### ISSUE TITLE
MediaInfo CLI read Menu ONLY

### ISSUE THREAD

**Issue by peter8777555** [MediaArea/MediaInfo#907]
OS : Windows 11
MediaInfo GUI/CLI : V24.06

I want MediaInfo CLI read Menu ONLY,but MediaInfo CLI shows ALL informations.

MediaInfo --Output=Menu;"%%MenuID/String%%" 1.mkv

![z1](https://github.com/MediaArea/MediaInfo/assets/29886853/0e3913d2-b1e9-47b0-a42d-b17de16d170f)

**Comment by JeromeMartinez** [comment]
You need to use MediaInfo CLI. Here you use MediaInfo GUI and MediaInfo GUI doesn't (yet) support CLI related commands.
https://mediaarea.net/MediaInfo/Download/Windows

**Comment by peter8777555** [comment]
The GUI snapshot is a sample.
I use CLI.

MediaInfo --Output=Menu;"%%MenuID/String%%" 1.mkv

**Comment by JeromeMartinez** [comment]
> The GUI snapshot is a sample.

would have been better to copy/paste the CLI output for avoiding the mistake.

> MediaInfo --Output=Menu;"%MenuID/String%" 1.mkv

OK, I see, it is fine with everything but Menu, I need to dig in code for that

> Can i get 3,905 kb/s or 3905 kb/s ?

MediaInfo.exe "--Language=  Config_Text_ThousandsSeparator;,"
(2 spaces after "=")

**Comment by peter8777555** [comment]
>would have been better to copy/paste the CLI output for avoiding the mistake.

My fault.

>MediaInfo.exe "--Language= Config_Text_ThousandsSeparator;,"
>(2 spaces after "=")

Yes,it works.

>OK, I see, it is fine with everything but Menu, I need to dig in code for that

I have tested General,Video,Audio,Text and works well.
Do you have test Chapter and Image ?
