### ISSUE TITLE
Mapping Color Config Semantics

### ISSUE THREAD

**Issue by Ironclad17** [MediaArea/MediaInfo#911]
I wanted to create a simple script that maps the colorspace and pixel format values from MediaInfo to several video encoders that use slightly different syntax. Please see the subsection 6.4.2, 6.7.3, and 6.7.4 of the [AV1 Bitstream & Decoding Process Specification](https://aomediacodec.github.io/av1-spec/av1-spec.pdf). Is there any documentation clarifying this? FFmpeg for example provides a list of values for supported pixel formats, color_primaries, color_trc, colorspace, and color_range: https://ffmpeg.org/ffmpeg-codecs.html#Codec-Options

**Comment by JeromeMartinez** [comment]
For the moment it is only in https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfo/Video/File_Mpegv.cpp#L33-L99

**Comment by Ironclad17** [comment]
Thank you! This was exactly what I was looking for!
