### ISSUE TITLE
[UI] [24.06] About dialog has text cut

### ISSUE THREAD

**Issue by superbonaci** [MediaArea/MediaInfo#913]
Some text is cut and other is very close to edges

![MediaInfo_24.06_About](https://github.com/user-attachments/assets/6021d256-405d-47e1-acba-68e20be9fef3)

**Comment by superbonaci** [comment]
When installing the graph plugin there are some issue also.

**Comment by JeromeMartinez** [comment]
> When installing the graph plugin there are some issue also.

Could you be more precise?

**Comment by cjee21** [comment]
No text is cut but the close to edges issue should already be fixed by https://github.com/MediaArea/MediaInfo/commit/d5e8e94d3c3c67c68c041d1d3ab3ac5832eb29cf

**Comment by superbonaci** [comment]
> > When installing the graph plugin there are some issue also.
> 
> Could you be more precise?

![graph](https://github.com/user-attachments/assets/33df64bb-ec77-40be-84a3-827960f4c157)
