### ISSUE TITLE
MediaInfo pulling "Identity" Matrix Coefficients

### ISSUE THREAD

**Issue by joe-sciame-wm** [MediaArea/MediaInfo#921]
Hi Jerome,

We have a set of files that are pulling "Identity" as the Matrix Coefficients. I tried inspecting the atoms on the MOV file but couldn't yet determine where the "Identity" is coming from. If I send you the file could you let me know where it is being pulled from so that I could determine what it means.  I see the `matrix_coefficients_Original` is what we'd expect to see which is BT.709.

> colour_description_present               : Yes
colour_description_present_Source        : Container / Stream
Color primaries                          : BT.709
colour_primaries_Source                  : Container / Stream
Transfer characteristics                 : BT.709
transfer_characteristics_Source          : Container / Stream
Matrix coefficients                      : Identity
matrix_coefficients_Source               : Container
matrix_coefficients_Original             : BT.709
matrix_coefficients_Original_Source      : Stream
Menus                                    : 0

**Comment by JeromeMartinez** [comment]
From the MediaInfo report, I bet that the raw stream (AVC, HEVC, ...) is correct with BT.709 and the MOV `colr` has matrix_coefficients of 0.
I could say more if you share the file (in private if needed) or if you share the [MediaTrace](https://mediaarea.net/MediaTrace) of the file (look for the `colr` part, only this part is needed).

**Comment by joe-sciame-wm** [comment]
Hi Jerome,

Attached is the MediaTrace. What doe sit mean to have a Matrix Index of 0?

***@***.***

Thanks,

JOE SCIAME
Principal Architect| Media Workflows | Media Supply Chain
C. 470-809-2479 | slack: jsciame 
[signature_374330048]


From: Jérôme Martinez ***@***.***>
Date: Wednesday, August 7, 2024 at 11:44 AM
To: MediaArea/MediaInfo ***@***.***>
Cc: Sciame, Joe ***@***.***>, Author ***@***.***>
Subject: Re: [MediaArea/MediaInfo] MediaInfo pulling "Identity" Matrix Coefficients (Issue #921)

From the MediaInfo report, I bet that the raw stream (AVC, HEVC, ...) is correct with BT.709 and the MOV colr has matrix_coefficients of 0.
I could say more if you share the file (in private if needed) or if you share the MediaTrace<https://urldefense.com/v3/__https:/mediaarea.net/MediaTrace__;!!AQdq3sQhfUj4q8uUguY!ieva3Onceg8cb_iLVzNlYbaLJpeN9gSFi_JZtUzMU_Wjqdv2YcEK3AJu6z8SIrf-Jgc5AzW4QTh65QEb6cHjn88DQyZu$> of the file (look for the colr part, only this part is needed).

**Comment by JeromeMartinez** [comment]
In your file, MOV matrix index is 0 (Identitiy) and raw stream matrix index is 1 (BT.709), there is an incoherence in your file and MediaInfo shows that, and also prioritizes MOV matrix index.
So whatever the definition of values, your file is buggy as MOV and raw stream shall have same value (MOV values are expected to be a copy of the raw stream values, just easier to retrieve for a demuxer).

e.g. [H.265](https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-H.265-202309-S!!PDF-E&type=items) defines matrix index of 0 as:
Table E.5 – Matrix coefficients interpretation using the matrix_coeffs syntax element
Value Matrix Informative remark
0 Identity The identity matrix.
Typically used for GBR (often referred to as RGB); however, may also be
used for YZX (often referred to as XYZ)
IEC 61966-2-1 sRGB
SMPTE ST 428-1 (2006)
See Equations E-31 to E-33
Y = Round( G ) (E-31)
Cb = Round( B ) (E-32)
Cr = Round( R ) (E-33)

In other terms, matrix index of 0 does not mean e.g. "unknown" (it is value 2) but says explicitly that there is no transformation of RGB to YUV, i.e. that that the stored pixels are RGB (or XYZ).

If it is not the reality, the file needs to be fixed for being conform (replace matrix index 0 by matrix index 1).
