### ISSUE TITLE
Windows 11 V24.11 Opens with blank white screen

### ISSUE THREAD

**Issue by wex1248** [MediaArea/MediaInfo#942]
Every time I invoke it (right click), it display a blank white screen. I have to Select 'View' for it to to display the info. Went back to 24.06; works fine.

**Comment by cjee21** [comment]
> Every time I invoke it (right click), it display a blank white screen. I have to Select 'View' for it to to display the info. Went back to 24.06; works fine.

To make sure I am reproducing the same issue, do you mean that you have MediaInfo set to open in HTML view by default and when you right click on a file in Windows File Explorer and invoke MediaInfo in the context menu, it shows "(You must at least open one file)" and will only work after you change views?

**Comment by cjee21** [comment]
Interestingly it is only reproducible when installed and works properly when using the copy in C++Builder's build directory.

Also looks like something unexpected is happening when set to open HTML view by default. WebView2 seems to be used (`FormShow`/`Refresh` called) before `TMainF` constructor is run causing WebView2 UDF directory to be default and potentially the blank output.
