### ISSUE TITLE
Ctrl+A shortcut not working anymore.

### ISSUE THREAD

**Issue by Cornstalk8567** [MediaArea/MediaInfo#950]
Unable to select all text using the Ctrl+A keyboard shortcut on Windows. This was not an issue in v. 24.06, however it is present in the latest build (v. 24.11). Right clicking and then selecting "Select all" from the context menu still works, but adds an extra step. A quick resolve would be greatly appreciated. Thanks.

**Comment by JeromeMartinez** [comment]
[fixed]()https://github.com/MediaArea/MediaInfo/pull/946, please try [this snapshot](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20241109-2/MediaInfo_GUI_24.11.20241109_Windows.exe).

**Comment by cjee21** [comment]
Fixed in 24.12
