### ISSUE TITLE
Wording: Term "general" vs "container"

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaInfo#970]
Hi :)

Legacy terminology by MediaInfo is "General" for container-specific information.

I wanted to ask years ago if this could be changed to "Container" :grin: 
(to make it easier/consistent for newcomers (for me to teach))

Now I've noticed that in MediaInfo on macOS, it seems to be renamed to "Container" about 1-2y ago. :partying_face: 

But in v24-11 on Linux, it's still called "General".

**Comment by JeromeMartinez** [comment]
> I wanted to ask years ago if this could be changed to "Container" 😁

It is always complicated to change something already used, and there is also a debate between "container" and "wrapper" :-p.
In theory I am fine with changing to "container" ("wrapper" being so much MXF only...) but in practice I am very reluctant to change that nowadays, the risk is maybe not worth it compared to the advantages of changing... And maybe it should be in a more global change, other terminologies are criticized e.g. "color space"... But well, I am not motivated now to face the complains if I change something.

In the meantime, "General" and "Container" are synonyms in MediaInfo.

> Now I've noticed that in MediaInfo on macOS, it seems to be renamed to "Container" about 1-2y ago. 🥳

Where?
I see "General" everywhere also on macOS.

**Comment by JeromeMartinez** [comment]
About the risks... note that the word "General" is in the XML, changing only the text output would create a difference between the XML and the text output, changing all would break a lot of third party tools.
It is the kind of change very difficult to do, the cost of choices made 25 years ago...

(and I add "MPEG-4" instead of "MP4" for a container format :( )

**Comment by pjotrek-b** [comment]
Thanks for the quick reply!
I totally get it.

But you did change it to "container" in the macOS build, right?
(I can't check it now, but I'm very sure I saw it when I did workshops...)

**Comment by JeromeMartinez** [comment]
> But you did change it to "container" in the macOS build, right?

I don't see where, either the free version or the Mac App Store version.
