### ISSUE TITLE
About curl-ca-bundle.crt

### ISSUE THREAD

**Issue by cjee21** [MediaArea/MediaInfo#974]
I noticed `curl-ca-bundle.crt` is supposed to be in CLI version as well
https://github.com/MediaArea/MediaInfo/blob/731eb35cc1e5b5b8da8e9117bde71cb5a12c9f74/Release/Release_CLI_Windows_x64.bat#L31

However, it is missing in the official release
![Screenshot 2024-11-26 161954](https://github.com/user-attachments/assets/a4c947ee-7f7e-46af-b361-844372f89e7f)

I am not sure if it is even used/needed as opening https links appear to work without it. The GUI version also opens https fine if `curl-ca-bundle.crt` is deleted. If not mistaken, curl uses Windows cert store if built using schannel / WinSSL backend instead of OpenSSL.

https://github.com/MediaArea/MediaArea-Utils-Binaries/blob/master/Windows/libcurl/curl-ca-bundle.crt is also (very) outdated.

**Comment by cjee21** [comment]
Comparing the ZIP of x64 CLI to i386 one, x64 is missing `Contrib` folder and `curl-ca-bundle.crt`.

**Comment by JeromeMartinez** [comment]
> If not mistaken, curl uses Windows cert store if built using schannel / WinSSL backend instead of OpenSSL.

Right. We forgot to remove `curl-ca-bundle.crt` when we switched to to Schannel.

**Comment by cjee21** [comment]
> Right. We forgot to remove `curl-ca-bundle.crt` when we switched to to Schannel.

Want me to make a PR to remove it from build scripts?

Do you want a PR for signing the uninstaller too?

**Comment by JeromeMartinez** [comment]
> Want me to make a PR to remove it from build scripts?

Yes :).

> Do you want a PR for signing the uninstaller too?

Yes :).

PS: our build farm is nearly ready for having MSVC2022 for your Win11 PR.
